### ISSUE TITLE
[BUG]: Broken wikipedia link for Windows Push Notification Service

### ISSUE THREAD

**Issue by MarcusOtter** [undergroundwires/privacy.sexy#101]
### Description
First of all, cool project 🚀!

I selected the "**Standard** mode" and noticed "Windows push notification service" was disabled by default, which seems odd to me (notifications seems like pretty important functionality). So when I hovered over the information button for this setting, I got this link: https://en.wikipedia.org/wiki/Windows_Push_Notification_Service#Privacy_Issue.

It seems like it tries to link to a "Privacy Issue" section in this wikipedia article, but that section seems to have been removed. Nothing in this wikipedia article explains what issues this feature is causing, and more importantly, as a user I still don't understand what it means to disable "Windows push notification service". 

### Reproduction steps
1. Find the "Windows Push Notification Service" setting
2. Hover over the information button
3. Click the information button
4. See no information that a user that clicked the information button is interested in reading😄 

### Expected behavior
Explain more why this setting is disabled, and how this really affects the OS.

### Screenshots
![image](https://user-images.githubusercontent.com/35617441/138301909-c0b16f9f-3a57-47ea-93a5-bcdbb15d5263.png)

### Distribution
Using Firefox on Windows

**Comment by undergroundwires** [comment]
Closing this as both are now implemented and released. Thank you again and feel free to report if there's anything else.
