### ISSUE TITLE
Spotify won't play content, trying to find what privacy setting / block caused it?

### ISSUE THREAD

**Issue by rayheffer** [undergroundwires/privacy.sexy#108]
Windows 10
Spotify (desktop app, not Windows Store)

You can reproduce this issue if you enable all privacy options. Try playing a track on Spotify and it will say it's unavailable / offline.

I am trying to find which setting has blocked this. It's unable to play any content.

**Comment by undergroundwires** [comment]
You should be careful with running "All". It's not meant for daily OS users. We should probably have better warning mechanism for this with a potential "Are you sure what youre doing?" dialog.

I can recommend reverting back all system apps. It's often one of them that causes issues.

**Comment by rayheffer** [comment]
I wasn't sure which one caused the issue, but it was on a VM so no harm done :)  I want to use it on my main PC, but I am having trouble narrowing down which setting breaks Spotify. I'll look at the system apps again, thanks!

**Comment by bardiarajabi** [comment]
@rayheffer You have disabled windows DRM from accessing internet-connection
[Spotify Uses DRM.](https://www.defectivebydesign.org/spotify)
