### ISSUE TITLE
[BUG]: "SystemSettings.exe - Stack-based buffer" when accessing network settings

### ISSUE THREAD

**Issue by Permanently** [undergroundwires/privacy.sexy#110]
### Description

When simply running the **strict** script along with a few other tiny things, [this pops up](https://i.stack.imgur.com/k8ViG.png) when trying to access network settings.

### OS

Windows 10 Pro (Version 21H1, OS Build 19043.1415)

### Reproduction steps

1. Select "Strict" on privacy.sexy
2. Tick some other stuff (find attached)
3. Run script
4. Restart
5. Try to navigate to Network Settings
6. Observe

### Scripts

[Here.](https://www.toptal.com/developers/hastebin/odomudeqes.bash)

### Screenshots

[Here.](https://i.stack.imgur.com/k8ViG.png)

### Additional information

Forgot to add, hence the edit - I thought my computer was just acting up and thought it was weirder when I still had the issue after I reset and installed all my stuff back on, but I managed to pinpoint it to this script when I ran the same one on my laptop and got the same issue.

**Edit 2:** Just tested on a VM, 100% something in the strict script at least - didn't add anything extra this time, yet got the same error

**Comment by Permanently** [comment]
Found the fix, and it's not what I thought it would be.

[Re-enabling Windows Push Notification Service](https://www.toptal.com/developers/hastebin/mucofetade.bash) seems to have Network Settings functioning normally again. Why? Not sure.

Probably should change the script or remove the option from the Strict choice, though.

**Comment by undergroundwires** [comment]
I tested this on W10 21H1 and W11 21H2 and can reproduce the problem on W10 but not on W11.

This script [disables three services](https://github.com/undergroundwires/privacy.sexy/blob/0.11.2/src/application/collections/windows.yaml#L4696-L4720):

1. System service: `WpnService`
2. User service (system-wide): `WpnUserService`
3. User service (per-user): `WpnUserService_{random-suffix}`

All three services exist in both Windows 10 and Windows 11. In Windows 10, only disabling the second service causes this problem.

Last two services were introduced in the last version with #101 . As we also realized in #101, we don't have enough proof or documentation that this service is privacy invasive except an old wikipedia article. So I agree that this should be unrecommended. We don't have enough justification to keep a breaking script recommended.

But how should we unrecommend it? Should we unrecommend all three services? Or only second one that's breaking? Or should we write custom logic to not disable it on Windows 11 but only on Windows 10? I will think about it.

This is great contribution btw. Very clear bug report that's easy to understand and replicate with all necessary information and you even provide a solution ❤️.  It'd be great to see you around more in our small community.

**Comment by Permanently** [comment]
Originally I was going to say use `systeminfo` to figure out if it's Windows 10 or 11, then go through with what you suggested with keeping `WpnUserService` for Win10. However, I've just had a quick look at the Wikipedia page and seen that the privacy issue that was added [had no sources to back it](https://en.wikipedia.org/w/index.php?title=Windows_Push_Notification_Service&oldid=835121797), and that a revision of the page early of last year [removed the privacy section](https://en.wikipedia.org/w/index.php?title=Windows_Push_Notification_Service&oldid=1009011367). I can only assume it's a myth due to the lack of sources, and it'd only be fair to say that until there's a conclusive study that it's purely for push notifications and nothing more.

> This is great contribution btw. Very clear bug report that's easy to understand and replicate with all necessary information and you even provide a solution ❤️. It'd be great to see you around more in our small community.

Thank you! I spent about 45 minutes trying to figure out which privacy package was up to no good in a VM, and out of everything I didn't expect push notifications to be interfering with Network Settings at all. I might have another bug in-store for you as there's a separate issue I've come across related to Windows 10 internet, but I can't tell you yet whether it's privacy.sexy related or a third-party issue 😝

**Comment by undergroundwires** [comment]
Hi, 

Thanks for your input. I've done some more research about this service. Wikipedia article was simply stating that it circumvents the anonymity provided by VPN and reveals real host IP. It did not have good citation and I have not tested this. But I also found in [official Microsoft documentation](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/windows-push-notification-services--wns--overview) that it's clearly documented that this service shares data with third party developers through Microsoft services. There's more in-depth discussion about its privacy issues in [BleepingComputer forums](https://www.bleepingcomputer.com/forums/t/653656/network-security-concerns-with-netstat-output/page-3).

It sends data about you, disabling it works fine on Windows 11, and it does not introduce security risks. I think we should keep it as "Strict" for a while. I pushed a commit where I added warning message on terminal output and  document that it breaks stuff on Windows 10. I implemented a better way to document scripts that I will publish in next minor release.

P.S.: This is time-consuming but you've found a perfect way of debugging 👍️.

**Comment by bardiarajabi** [comment]
I also experienced this problem too!
Hoping that this problem gonna fixed!
P.S.: @Permanently @undergroundwires I googled this problem on google but it was just SFC /scannow and dism /online /cleanup-image /restorehealth (that's common)
