### ISSUE TITLE
Help, can't install a software

### ISSUE THREAD

**Issue by heywolf15** [undergroundwires/privacy.sexy#120]
Sorry for asking help for this
I already revert the script "Disable Windows Installer Always install with elevated privileges"
But it still failed to start, I don't know what scripts that causing this

![explorer_h1978hgwbB](https://user-images.githubusercontent.com/34807171/153353055-cf471c20-8244-4217-9409-226012313792.png)

**Comment by heywolf15** [comment]
@bardiarajabi  It is in admin
Can't find failure reason,  there's only 4 tabs on the properties
it's not .msi

If someone wants to try it on Basic or Strict set
https://puresoftapps.blogspot.com/2018/04/realtek-apo-driver.html

**Comment by bardiarajabi** [comment]
@heywolf15 try downloading from official website not a Blog (its 2022 btw)
Did you check the services.msc ?? (Dolby DAX API Service)
to open services list press meta(windows key) + R and then type `services.msc` and then check the service

**Comment by heywolf15** [comment]
@bardiarajabi That's the official site, try search about it before saying that (it's 2022 btw)
Here's the thread on the forum https://www.techpowerup.com/forums/threads/making-audio-enhancers-work-on-windows.244309/
I know how to do that, I just don't know where to find the "Why its fail"
I'm just gonna reset

**Comment by undergroundwires** [comment]
Thanks for your guidance @bardiarajabi , and you're right about the blog post.

This installer looks very fish. Drivers run with such high privileges and should only be installed from official sources, not from a blog post that links to a google docs link that links to a mediafire URL. This is how a lot of malware is being distributed. Out of curiosity I checked it and kaboom, these files are marked as malware. See [virus total 1](https://www.virustotal.com/gui/file/c7208a74c1a2e6e03663475cd328995b5dd6c1aa01102bd329ec9fa3c9758bef), [virus total 2](https://www.virustotal.com/gui/file/a9e322db031c52033e0bb42042ee7c197a173e90360388b25aff71e9bee4f46f).

I do not know what they are but I don't recommend anyone running those. 

This does not seem to have anything to do with the script mentioned ("Disable Windows Installer Always install with elevated privileges"). And to my knowledge there's no script here that takes away your privileges to start system services. This can somehow be side-effect of any other script, in that case we need to be able to reproduce this. In this case you need to provide the generated script file (all of the scripts).

**Comment by bardiarajabi** [comment]
@undergroundwires its definitely false-positive cuz its just eset antivirus which is no longer on top AVs
