### ISSUE TITLE
[HELP] I need license telemetry back please

### ISSUE THREAD

**Issue by TheMystery28** [undergroundwires/privacy.sexy#123]
`
@echo off
:: https://privacy.sexy — v0.11.3 — Fri, 18 Feb 2022 21:23:25 GMT
:: Ensure admin privileges
fltmc >nul 2>&1 || (
    echo Administrator privileges are required.
    PowerShell Start -Verb RunAs '%0' 2> nul || (
        echo Right-click on the script and select "Run as administrator".
        pause & exit 1
    )
    exit 0
)

:: ----------------------------------------------------------
:: ----------------Disable license telemetry-----------------
:: ----------------------------------------------------------
echo --- Disable license telemetry
reg add "HKLM\Software\Policies\Microsoft\Windows NT\CurrentVersion\Software Protection Platform" /v "NoGenTicket" /t "REG_DWORD" /d "1" /f
:: ----------------------------------------------------------

pause
exit /b 0
`

Can someone to do the reverse script please?

**Comment by undergroundwires** [comment]
Hi @TheMystery28 ,
Happy that you found a solution. Both Windows 10 and Windows 11 comes without this key by default. So we can just delete it to match the default OS behavior, such as:

```batchfile
reg delete "HKLM\Software\Policies\Microsoft\Windows NT\CurrentVersion\Software Protection Platform" /v "NoGenTicket"  /f
```

You need to run this command as administrator. I will add missing revert behavior to the application in next patch.

**Comment by undergroundwires** [comment]
Hi @TheMystery28 ,

Both Windows 10 and Windows 11 comes without this key by default. So we can just delete it to match the default OS behavior, such as:

```batchfile
reg delete "HKLM\Software\Policies\Microsoft\Windows NT\CurrentVersion\Software Protection Platform" /v "NoGenTicket"  /f
```

You need to run this command as administrator. I will add missing revert behavior to the application in next patch.

Can I ask the reason behind your wish to bring the telemetry back? Did this script cause an unexpected behavior for you?
