### ISSUE TITLE
Portable Windows app

### ISSUE THREAD

**Issue by SonaliBendre** [undergroundwires/privacy.sexy#127]
### Proposed solution

I hate setup.exe Please provide portable version
### Additional information
NA

Can create a scoop package

**Comment by undergroundwires** [comment]
Hi @SonaliBendre, this was requested at #95 as well so I'm closing it in favor it. I will eventually add this but prioritize some other features/bugs for now. I'll add instructions there about how to solve this if you'd like to send a PR.
