### ISSUE TITLE
[BUG]: Windows Defender Uninstaller Script Doesn't Remove the MsMpEng.exe

### ISSUE THREAD

**Issue by jeffogu** [undergroundwires/privacy.sexy#128]
Description
Windows Defender uninstaller script doesn't remove the MsMpEng.exe. 
Started it with adminstrator privileges and tried it for a few times again but nothing changed.

OS
Windows 10 x64 Pro Version 21H1

**Comment by brootware** [comment]
Hi @jeffogu , could you give a more specific on which particular script it is? So we can reproduce. Please use the bug report's instructions on reproduction steps

**Comment by bardiarajabi** [comment]
@jeffogu I don't think that it is supposed to [do that](https://0bin.net/paste/ZEpehZgO#PRorVhN3tynm0zZJgJni59CRWWkbuO2wVnd9rKYISRf)
So the flag should be a feature request if I'm not wrong.

**Comment by undergroundwires** [comment]
Fix released as part of [0.13.7](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.7) 🚀. The file is now removed/moved. Feel free to test it and open new issue if there are any other issues. Thank you again.
