### ISSUE TITLE
[BUG]: All cloud services can't sync files

### ISSUE THREAD

**Issue by whinix** [undergroundwires/privacy.sexy#131]
After running the script all my cloud sync services stopped working. 

I'm on Windows 10, here's the script: https://rentry.co/cxtfu

I have already tried to revert the deny app access (although my cloud apps do not come from MS Store), deny online content in explorer and NTP server change.

Both my dropbox and MEGA Sync are still dead.

**Comment by whinix** [comment]
Reverted windows DRM internet access in registry, still doesn't work

**Comment by undergroundwires** [comment]
Hi @whinix , thanks for the report. If we can't reproduce this, we can't help you.

I need more details. You can refer to [issue template](https://raw.githubusercontent.com/undergroundwires/privacy.sexy/0.11.3/.github/ISSUE_TEMPLATE/1-bug-report-scripts.md) as a guide for what more information is needed. Good idea to provide steps from scratch including versions of software used and screenshots where we can verify functionality before running the script, and verify that it does not work after running script.

**Comment by whinix** [comment]
> Hi @whinix , thanks for the report. If we can't reproduce this, we can't help you.
> 
> I need more details. You can refer to [issue template](https://raw.githubusercontent.com/undergroundwires/privacy.sexy/0.11.3/.github/ISSUE_TEMPLATE/1-bug-report-scripts.md) as a guide for what more information is needed. Good idea to provide steps from scratch including versions of software used and screenshots where we can verify functionality before running the script, and verify that it does not work after running script.

What do you need in addition to the script file i posted ? One of the tweaks must interfere with the way file syncing works with cloud apps. Any ideas what could that be ?

**Comment by whinix** [comment]
I have installed iCloud for Windows to check if Dropbox/Mega was a coincidence or a server side issue but it doesn't work either

**Comment by whinix** [comment]
> Hi @whinix , thanks for the report. If we can't reproduce this, we can't help you.
> 
> I need more details. You can refer to [issue template](https://raw.githubusercontent.com/undergroundwires/privacy.sexy/0.11.3/.github/ISSUE_TEMPLATE/1-bug-report-scripts.md) as a guide for what more information is needed. Good idea to provide steps from scratch including versions of software used and screenshots where we can verify functionality before running the script, and verify that it does not work after running script.

I have reverted all the following categories: 

- Meltdown and Spectre Protection
- Increase Cryptography on ISS

That fixed the issue.

**Comment by undergroundwires** [comment]
Happy that you solved it 🥳

>     * Meltdown and Spectre Protection
>     * Increase Cryptography on ISS

Thank you for the report back.

If you could apply them back and verify that the apps break would be nice contribution the community. Because this way we can for sure know that it's one of these scripts is root cause and isolate to problem to figure out which one is causing it. As I cannot reproduce your environment (or don't know how to), I cannot test it myself. If we find out what exactly is causing it we can remove that script from recommendation and document the behavior.

But you don't need to do any of it 😀 This is a hobby thing for us which we improve if we feel like it. Let me know if you'd any other issue/feedback and have a nice week.

**Comment by whinix** [comment]
> Happy that you solved it 🥳
> 
> > ```
> > * Meltdown and Spectre Protection
> > * Increase Cryptography on ISS
> > ```
> 
> Thank you for the report back.
> 
> If you could apply them back and verify that the apps break would be nice contribution the community. Because this way we can for sure know that it's one of these scripts is root cause and isolate to problem to figure out which one is causing it. As I cannot reproduce your environment (or don't know how to), I cannot test it myself. If we find out what exactly is causing it we can remove that script from recommendation and document the behavior.
> 
> But you don't need to do any of it 😀 This is a hobby thing for us which we improve if we feel like it. Let me know if you'd any other issue/feedback and have a nice week.

Alright, so i re-applied Meltdown and Spectre Protection and restarted - no issues. Then i ticked all tweaks from "Increase Cryptography on ISS" except for disabling SHA1/MD5. The result is that MEGA Sync works but Dropbox doesn't. 

So it looks like cloud services are dependent on some of the disabled encryption and MEGA needs either SHA1/MD5 for file comparing/indexing file versions. 

Enabling all of that one by one and restarting each time is too time consuming for me, maybe i will do that one day but i've had enough for today. Good luck with your project.

**Comment by undergroundwires** [comment]
Thank you a lot for your insights. I thought they were server only configurations. A quick research show me that they're not. So even "IIS" naming here is wrong. They are not ISS only. They may be the issue with other bugs reported before as well. I will rename this category completely.

**Comment by undergroundwires** [comment]
I've reworked network-related scripts completely in [0.13.3](https://github.com/undergroundwires/privacy.sexy/releases/edit/0.13.3), it should solve this issue along with others.

**Comment by undergroundwires** [comment]
I've reworked network-related scripts completely in [0.13.3](https://github.com/undergroundwires/privacy.sexy/releases/edit/0.13.3), it should solve this issue along with others. The category is also renamed.
