### ISSUE TITLE
Thank you for this tool.

### ISSUE THREAD

**Issue by Prajwal-Koirala** [undergroundwires/privacy.sexy#133]
Thank you for this tool, it's super useful, found some bugs, but I am guessing it will be ironed out overtime.
- Prajwal

**Comment by undergroundwires** [comment]
@Prajwal-Koirala , thank you a lot ❤️ Happy that you liked it and found it useful. It will get better with cooler versions in each version and I wish to find more time to put into it.

I'd love to here the bugs you found. The bugs are typically prioritized higher.

Feel free to create new issues for your ideas or bugs mentioned so we can solve them.
