### ISSUE TITLE
Systemrequirements ; Windows 10,11 ...

### ISSUE THREAD

**Issue by blackcrack** [undergroundwires/privacy.sexy#134]
### Problem description

In the Readme.md is not shown a Systemrequirement like :  
Requirements: Windows 2000,  Windows XP, Windows 10, Windows 11, ... ;)

### Proposed solution

add at the Readme.md
Requirements: Windows 10, Windows 11  
  
  
  
### Alternatives considered

nope
### Additional information

nope...

--
a wonderful day :)
best

**Comment by undergroundwires** [comment]
Thank you for your idea and time put into reporting this @blackcrack. We should fix this.

Do you mean minimum requirements to run the desktop application or run the generated scripts?

For system requirements to run the app we can link to [Electron supported platforms](https://www.electronjs.org/docs/latest/tutorial/support#supported-platforms) or copy paste from there.

**Comment by blackcrack** [comment]
yes, minimum, like this.. take a look :  
https://github.com/sandboxie-plus/Sandboxie  
  
and a changelog is definitely not wrong ;)
  
thank you for resonance and appreciation

you can close it, if done :)
best regards

**Comment by undergroundwires** [comment]
Thanks for the example. It is a very clean way of providing download links.

FYI, this would like:

- **Windows**: Windows 7 and later, 32-bit or 64-bit.
- **Linux**: Ubuntu 14.04, Fedora 24, Debian 8 and later.
- **macOS**: macOS 10.11 and later.

I think it would be nice to create like `privacy.sexy/download` page that GitHub page that would link to. It would then have all this information. It requires routing support to resolve `/download` URL that privacy.sexy now lacks. I will and this when routing is here. Routing would also enable sharable URLs for scripts.

P.S.: I keep [release logs for every release](https://github.com/undergroundwires/privacy.sexy/releases) and [CHANGELOG.md](https://github.com/undergroundwires/privacy.sexy/blob/0.11.4/CHANGELOG.md).

**Comment by blackcrack** [comment]
if a program itself is so convincing and good, you don't need a huge page ..
the Info about the program clean and so far full in the Readme.md
and the Release page linking as download is pretty well as enough you know.. 
you see the Programpage from David Xanatos..  and this is totally enoug.. the good thing is, 
if the User Watch your Programmpage is there a possible for Custom Notification..
and if you move a release up and make a new release can the user configuration this Custom 
watch to know to be there a new version on the releasepage via mail if it configuring like this..
so, concentration you first in a simple steps and add only the 
Requirements and maybe changelog link of it, easy to make before you make huge other things..
so, add the requirements at the Readme.md and close this issue ;)
Step for step :)

best
Blacky

**Comment by bardiarajabi** [comment]
@undergroundwires What about arch-based Linux distros?😊

**Comment by blackcrack** [comment]
closebot

**Comment by undergroundwires** [comment]
I'm preparing documentation for this, did any one try privacy.sexy on Arch Linux? Now that we have privacy scripts for Linux, this is more relevant. @bardiarajabi are you around?

**Comment by undergroundwires** [comment]
See: [system-requirements.md](https://github.com/undergroundwires/privacy.sexy/blob/0.13.3/docs/desktop/system-requirements.md)

**Comment by undergroundwires** [comment]
See: [system-requirements.md](https://github.com/undergroundwires/privacy.sexy/blob/0.13.3/docs/desktop/system-requirements.md), feel free to open new isssues/PR for changes/improvements.
