### ISSUE TITLE
More comments would be great

### ISSUE THREAD

**Issue by karam72** [undergroundwires/privacy.sexy#138]
First of all tank you for this great application :)

### Problem description
I was searching to disable microphone driver from command line for my work laptop. Because I think IT is listening to us at home. I found a script on your project: "Deny app access to microphone". But I don't know anything about it. I research a little bit. I found this: https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-privacy#privacy-letappsaccessmicrophone-forcedenytheseapps

As I understand, the script disables the microphone for Windows Store apps and some desktop apps.

### Proposed solution
This is not a problem but I just want to ask if you can add more comments on the scripts, so we can understand better what is going on behind.

You can directly close the issue. I just want to tell you those.

Thank you again this great effort :heart:

**Comment by undergroundwires** [comment]
[0.13.4](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.4) is just released  🎉 and it adds comments for the category and every scripts, including information from your reference.

Thank you for the suggestion @karam72, feel free to give feedback if you're around.
