### ISSUE TITLE
[BUG]: Disabled Windows Insider Programme

### ISSUE THREAD

**Issue by f-x1-1** [undergroundwires/privacy.sexy#139]
### Description
The script has disabled windows insider programme, the page is empty.  Unable to use windows insider updates.

### OS
OS Build: 22000.613

### Reproduction steps
Open the windows insider programme page
Notice the page is empty

### Expected Behaviour
Display windows insider build options

**Is there any reverse script?**

**Comment by affector** [comment]
![insider](https://user-images.githubusercontent.com/103291122/163553146-52db51b7-83ba-4dd4-977e-b38a2fd96c4b.jpeg)
next time use the search bar
