### ISSUE TITLE
 Enable Login for Windows Universal Apps

### ISSUE THREAD

**Issue by kiot389** [undergroundwires/privacy.sexy#140]
### Description

How can you enable Microsoft account logins on UWP apps? 
ProcMon shows me what keys are causing it.
I can't find which reverse script will let me login with apps like OneNote for Windows 10.  

### OS
Windows 11 Pro 22000.527

### Reproduction steps

The app splash screen launches and asks to pick an account to sign in with. 
Personal Microsoft account, Work or school account. 

I ran ProcMon, then click Sign In and see the registry keys that are breaking auth.
Attached is a summarized OneNote App log. I'm not sure what key or value to add back to the Registry. 

[privacy sexy scripts used.zip](https://github.com/undergroundwires/privacy.sexy/files/8638721/privacy.sexy.scripts.used.zip)
[OneNoteApp.log.docx](https://github.com/undergroundwires/privacy.sexy/files/8638762/OneNoteApp.log.docx)
![OneNote-Procmon](https://user-images.githubusercontent.com/36932098/167099303-ee0e12f5-dffd-42b3-af76-8dcb08a02d16.jpg)

**Comment by kiot389** [comment]
https://docs.microsoft.com/en-us/office365/troubleshoot/administration/disabling-adal-wam-not-recommended
-I'm going to run through the resolve sign-in steps to try to find what's up with this procmon activity when it doesn't login. 
Perhaps this set of registry keys is misleading. 

The TechNet article is really good.
"Disabling ADAL or WAM authentication as a solution to fix sign-in or activation issues can have adverse effects in your environment." So, perhaps its checking HKCU\Software\Microsoft\Office\16.0\Common\Identity\DisableAADWAM is a fallback attempt to get authenticated.

Microsoft 365 apps (for example, Office client apps) use Azure Active Directory Authentication Library (ADAL) framework-based 
[Modern Authenication](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-auth-for-office-2013-and-2016)  by default. ADAL enables features like MFA & Certs.

Microsoft 365 apps use [Web Account Manager ](https://docs.microsoft.com/en-us/azure/active-directory/devices/concept-primary-refresh-token#key-terminology-and-components) (WAM) for sign-in workflows.

On Windows devices, some of the security-related features are available exclusively via WAM and are otherwise not possible. Additionally, all future innovations will be implemented on WAM.

**Comment by dennyamarojr** [comment]
You disable/uninstall the following components


Some UWP apps required the Advertising.Xaml

:: ----------------------------------------------------------
:: ----------------Microsoft Advertising app-----------------
:: ----------------------------------------------------------
echo --- Microsoft Advertising app
PowerShell -ExecutionPolicy Unrestricted -Command "Get-AppxPackage 'Microsoft.Advertising.Xaml' | Remove-AppxPackage"
:: ----------------------------------------------------------

To login with Microsoft account you need this

:: Microsoft AAD Broker Plugin app (breaks Night Light settings, taskbar keyboard selection and Office app authentication)
echo --- Microsoft AAD Broker Plugin app (breaks Night Light settings, taskbar keyboard selection and Office app authentication)
PowerShell -ExecutionPolicy Unrestricted -Command "$package = Get-AppxPackage -AllUsers 'Microsoft.AAD.BrokerPlugin'; if (!$package) {; Write-Host 'Not installed'; exit 0; }; $directories = @($package.InstallLocation, "^""$env:LOCALAPPDATA\Packages\$($package.PackageFamilyName)"^""); foreach($dir in $directories) {; if ( !$dir -Or !(Test-Path "^""$dir"^"") ) { continue }; cmd /c ('takeown /f "^""' + $dir + '"^"" /r /d y 1> nul'); if($LASTEXITCODE) { throw 'Failed to take ownership' }; cmd /c ('icacls "^""' + $dir + '"^"" /grant administrators:F /t 1> nul'); if($LASTEXITCODE) { throw 'Failed to take ownership' }; $files = Get-ChildItem -File -Path $dir -Recurse -Force; foreach($file in $files) {; if($file.Name.EndsWith('.OLD')) { continue }; $newName =  $file.FullName + '.OLD'; Write-Host "^""Rename '$($file.FullName)' to '$newName'"^""; Move-Item -LiteralPath "^""$($file.FullName)"^"" -Destination "^""$newName"^"" -Force; }; }"
:: ----------------------------------------------------------

:: ----------------------------------------------------------
:: --------------Microsoft Accounts Control app--------------
:: ----------------------------------------------------------
echo --- Microsoft Accounts Control app
PowerShell -ExecutionPolicy Unrestricted -Command "$package = Get-AppxPackage -AllUsers 'Microsoft.AccountsControl'; if (!$package) {; Write-Host 'Not installed'; exit 0; }; $directories = @($package.InstallLocation, "^""$env:LOCALAPPDATA\Packages\$($package.PackageFamilyName)"^""); foreach($dir in $directories) {; if ( !$dir -Or !(Test-Path "^""$dir"^"") ) { continue }; cmd /c ('takeown /f "^""' + $dir + '"^"" /r /d y 1> nul'); if($LASTEXITCODE) { throw 'Failed to take ownership' }; cmd /c ('icacls "^""' + $dir + '"^"" /grant administrators:F /t 1> nul'); if($LASTEXITCODE) { throw 'Failed to take ownership' }; $files = Get-ChildItem -File -Path $dir -Recurse -Force; foreach($file in $files) {; if($file.Name.EndsWith('.OLD')) { continue }; $newName =  $file.FullName + '.OLD'; Write-Host "^""Rename '$($file.FullName)' to '$newName'"^""; Move-Item -LiteralPath "^""$($file.FullName)"^"" -Destination "^""$newName"^"" -Force; }; }"
:: ----------------------------------------------------------

:: ----------------------------------------------------------
:: --OneSync capability (breaks Mail, People, and Calendar)--
:: ----------------------------------------------------------
echo --- OneSync capability (breaks Mail, People, and Calendar)
PowerShell -ExecutionPolicy Unrestricted -Command "Get-WindowsCapability -Online -Name 'OneCoreUAP.OneSync*' | Remove-WindowsCapability -Online"
:: ----------------------------------------------------------

Based on kiot389, you also need this

:: Active Directory Domain Services and Lightweight Directory Services Tools capability
echo --- Active Directory Domain Services and Lightweight Directory Services Tools capability
PowerShell -ExecutionPolicy Unrestricted -Command "Get-WindowsCapability -Online -Name 'Rsat.ActiveDirectory.DS-LDS.Tools*' | Remove-WindowsCapability -Online"
:: ----------------------------------------------------------

Here's a file to fix this problem
[privacy-script-fix-microsoft-account-problem.zip](https://github.com/undergroundwires/privacy.sexy/files/8791687/privacy-script-fix-microsoft-account-problem.zip)

Download and run the bat file as admin, and them restart the computer. After reboot your computer, try sign in to Microsoft Store or office apps in windows.

**Comment by kiot389** [comment]
Thank You, it fixed the issue. Night Light & O365 Apps Sign-In are working.
