### ISSUE TITLE
Load a saved script

### ISSUE THREAD

**Issue by npapatheodorou** [undergroundwires/privacy.sexy#147]
Privacy.Sexy is a great toolbox to remove bloatware from the majority of os. The only drawback that I found is that when a user saves the script he can only runs it. That would be really helpful if the user could load a saved script and make modifications on it e.g. revert a change. From code perspective each selection should correspond to a piece of code. If this code is detected on the loaded script the corresponding selection should be ticked.

**Comment by undergroundwires** [comment]
Hi, thank you for issue. It's duplicate is #59 and it's already implemented, I just didn't have to chance to test it properly. Hope will it will make it to version `0.13.0` (I'll release next one with Linux support and then prioritize this).
