### ISSUE TITLE
[BUG]: Win 11 Disabling Defender Firewall services completely breaks start menu and windows explorer search

### ISSUE THREAD

**Issue by arman-ku** [undergroundwires/privacy.sexy#148]
After running the script and rebooting, i was unable to open the startmenu. When pressing the start menu key it would sometimes open up after a long waiting time but then close on its own after a few seconds.
Also, typing in the search field in windows explorer was not possible anymore. it wouldnt do anything.
After clicking the field a cmd window would sometimes pop up for a split second.

i tried reverting a lot of changes related to cortana because i thought that was the issue at first.
So maybe that was also necessary.

However, i wasnt able to use the search and open the start menu again until i reverted those 2 options:
- Disable Windows Defender Firewall service (breaks Microsoft Store and `netsh advfirewall` CLI)
- Disable Windows Defender Firewall Authorization Driver service (breaks `netsh advfirewall` CLI)

After rebooting, start menu and search would work again.

my script is attached as txt
[privacy-script.txt](https://github.com/undergroundwires/privacy.sexy/files/8996236/privacy-script.txt)

edit: build 10.0.22000.778 with all updates

**Comment by arman-ku** [comment]
(Also, just a side note, Add-AppxPackage will not work without the services disabled. Maybe there is a way to circumvent that, i haven't looked into it)

**Comment by undergroundwires** [comment]
This cannot be reproduced.
