### ISSUE TITLE
Feature addition to support linux

### ISSUE THREAD

**Issue by targetsmallx** [undergroundwires/privacy.sexy#150]

**Comment by undergroundwires** [comment]
Hi @targetsmallx , thanks for the issue. I've been working on Linux support for some time and been testing for months on different distros now. It works fine so far, and provides new functions that does not exist on other projects like proper snap/flatpak support. I attach a screenshot here to show work in progress. I'll try to get it ready and ship with next version soon, then close this issue. I would appreciate a lot your feedback later so we can make it even better.
![image](https://user-images.githubusercontent.com/15555035/192157748-3caf0e58-4c39-4f94-9b94-07e45e7530e6.png)

**Comment by undergroundwires** [comment]
Released in [0.12.0](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.0) 🚀
