### ISSUE TITLE
[Request] [W10] Some WinaeroTweaker options

### ISSUE THREAD

**Issue by nulledone** [undergroundwires/privacy.sexy#153]
File explorer starting folder switch to This PC
Disable Downloads blocking
Activate Windows Photo Viewer (Im unsure if it is already implemented)

**Comment by undergroundwires** [comment]
Thanks for the suggestions. Unfortunately Winaero Tweaker is closed-source and proprietary with a restrictive license so I'm not sure what it is doing, so I will just guess based on the names you mention here.

`File explorer starting folder switch to This PC`: This is unfortunately out-of-scope and does not increase privacy. I see that there is big interest for a more general tweaker than privacy only and our core engine would be able to support it easily. However, the scope is this project is now privacy, and there are some core features that I'd like to prioritize (like import export) before introducing extensibility or making a generic tweaker.

`Activate Windows Photo Viewer`: This seems to re-active legacy photo viewing app using registry [1]. It also feels out-of-scope.

`Disable Downloads blocking`: This one seems to increase privacy by removing metadata that could expose your behavior in favor of decreasing your security [2]. It can be added under `Privacy over security` as we already support the same function for macOS  under `Disable File Quarantine`.

I hope you understand that I want to prioritize more features before supporting more generic tweaks, thank you again for your suggestions and feel free to create issues for anything else that comes to the mind. I'd appreciate creating an issue for each tweak you'd like to see so we can track the progress for them individually.

[1]: https://www.itechtics.com/restore-photo-viewer/
[2]: https://www.stigviewer.com/stig/windows_10/2019-09-25/finding/V-63841

**Comment by undergroundwires** [comment]
Thanks for the suggestions. Unfortunately Winaero Tweaker is closed-source and proprietary with a restrictive license so I'm not sure what it is doing, so I will just guess based on the names you mention here.

**File explorer starting folder switch to This PC**: This is unfortunately out-of-scope and does not increase privacy. I see that there is big interest for a more general tweaker than privacy only and our core engine would be able to support it easily. However, the scope is this project is now privacy, and there are some core features that I'd like to prioritize (like import export) before introducing extensibility or making a generic tweaker.

**Activate Windows Photo Viewer**: This seems to re-active legacy photo viewing app using registry [1]. It also feels out-of-scope.

**Disable Downloads blocking**: This one seems to increase privacy by removing metadata that could expose your behavior in favor of decreasing your security [2]. It can be added under `Privacy over security` as we already support the same function for macOS  under `Disable File Quarantine`.

I hope you understand that I want to prioritize more features before supporting more generic tweaks, thank you again for your suggestions and feel free to create issues for anything else that comes to the mind. I'd appreciate creating an issue for each tweak you'd like to see so we can track the progress for them individually.

[1]: https://www.itechtics.com/restore-photo-viewer/
[2]: https://www.stigviewer.com/stig/windows_10/2019-09-25/finding/V-63841

**Comment by nulledone** [comment]
I totally understand the priority, thanks a lot for your detailed message. However, I've an opinion about photo viewer thing, I don't really use it since it certainly isn't optimized app constantly have issues while browsing many pictures but it will probably be useful for some people that have **removed the original photo viewer.**

**Comment by undergroundwires** [comment]
Thank you for your response, I just added configurations "Configure handling of downloaded files" under "Privacy over security" that will make it to next release.

I understand your point. It sounds indeed useful but I still don't understand how it can relate to increasing privacy or security. If you think that I'm missing something and it can lead to better privacy/security, please create a new issue with script request issue template so we can track progress of each request separately.

**Comment by undergroundwires** [comment]
Released in [0.12.0](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.0) 🚀
