### ISSUE TITLE
[BUG]: Failed to uninstall Edge

### ISSUE THREAD

**Issue by playgithub** [undergroundwires/privacy.sexy#154]
### Env
* OS: Windows 11 21H2 (OS Build 22000.739)
* Edge: 103.0.1264.44
* privacy.sexy: 0.11.4

### Options
![image](https://user-images.githubusercontent.com/3665590/176985688-8175c3dc-062c-446a-a7de-b892de9a145c.png)

### Problem
After applying the scripts, edge still works.

**Comment by theRoboxx** [comment]
It doesn't work fo me either:
Edition Windows 10 Pro
Version 21H2
OS build 19044.1766

**Comment by undergroundwires** [comment]
Hi, uninstallation of chromum-based edge is fixed and system app should work fine. Does latest versions work for you?

**Comment by playgithub** [comment]
> Hi, uninstallation of chromum-based edge is fixed and system app should work fine. Does latest versions work for you?

Yes, it works for Windows 11 Pro.

Thanks
