### ISSUE TITLE
[BUG]: Error in tooltip for the Strict preset

### ISSUE THREAD

**Issue by ChaseCares** [undergroundwires/privacy.sexy#160]
### Description

> There is a missing tooltip for the Strict preset, resulting in a NaN inside the tooltip.  It appears that there is a erroneous + on line 23 in the file [TheSelector.vue](https://github.com/undergroundwires/privacy.sexy/blob/38610424c2611bc3b236083f82dda8df824c77d8/src/presentation/components/Scripts/Menu/Selector/TheSelector.vue#L22)
> 
> I think this is fairly important as a user is not receiving a warning.

### Reproduction steps

> In the app or on the website, hover mouse over the 'Strict' preset.

### Expected behavior

> I would expect three tooltips to be preset, and no NaNs.

### Screenshots
![image](https://user-images.githubusercontent.com/13863948/184370185-64813127-37a3-44ee-8dcf-de4751b60f5e.png)

### Distribution

> All

**Comment by undergroundwires** [comment]
Thank you @ChaseCares  ❤️ Also thank specially for giving the whole context with the code. Sorry for updating a bit late but this has been fixed.
