### ISSUE TITLE
[Request] Fixing explorer search speed

### ISSUE THREAD

**Issue by kubinka0505** [undergroundwires/privacy.sexy#169]
### Problem description
Explorer search is very slow. That's it.
Not like I don't know about [Everything](https://www.voidtools.com/support/everything/), but I prefer to use built-in things. I'm sure there is a workaround for making explorer search faster.

### Proposed solution
I'm not into Windows - sorry - so the only thing I can propose is another button in the `Configure Programs` on the website.
Perhaps tweaking something in the registry, or even in system32 folder itself, but I'm not sure, obviously.

### Alternatives considered
Software in the link above.

**Comment by undergroundwires** [comment]
Hi @kubinka0505 , thank you for the suggestion, but this one this not add to any privacy enhancement that's the goal of the project. I plan to make a more generic variant of this project that will also support optimizations, but I have other priorities with this project now and also in the life (🙂) so no timeline is promised. Similar suggestions were made in [other issues](#https://github.com/undergroundwires/privacy.sexy/issues?q=+label%3Aout-of-scope+).

**Comment by rounk-ctrl** [comment]
These two commands disables the new search introduced in 19h2 (1909) which uses the SearchApp.exe and mixes local content with web content.
```
reg.exe add "HKCU\Software\Classes\CLSID\{1d64637d-31e9-4b06-9124-e83fb178ac6e}\TreatAs" /f /ve /t REG_SZ /d "{64bc32b5-4eec-4de7-972d-bd8bd0324537}"
reg.exe add "HKCU\Software\Classes\WOW6432Node\CLSID\{1d64637d-31e9-4b06-9124-e83fb178ac6e}\TreatAs" /f /ve /t REG_SZ /d "{64bc32b5-4eec-4de7-972d-bd8bd0324537}"
```
