### ISSUE TITLE
Add TLS 1.3 support warning

### ISSUE THREAD

**Issue by soyware** [undergroundwires/privacy.sexy#175]
TLS 1.3 is only officially supported since Windows 11, and was experimentally supported since 1903 before that. On my 1809, enabling TLS 1.3 registry key breaks .NET apps. There should be a warning about that.

**Comment by undergroundwires** [comment]
Thank you for the clean report and suggestions.

You're right, [Microsoft warns about it](https://learn.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-#tls-protocol-version-support):

> TLS 1.3 is supported starting in Windows 11 and Windows Server 2022. Enabling TLS 1.3 on earlier versions of Windows is not a safe system configuration.

TLS 1.3 will no longer be enabled on versions before Windows 11. Even the current version the script is running is Windows 10 and earlier, the script will refuse to complete:

![image](https://github.com/undergroundwires/privacy.sexy/assets/15555035/9a12de3b-3473-4f88-9011-e26078093847)

DTLS 1.3 seems to have [never been supported by Microsoft](https://learn.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-#tls-protocol-version-support). It was simply a bug to have it. It's changed to DTLS 1.2. and the script will refuse to run versions before 1607.

![image](https://github.com/undergroundwires/privacy.sexy/assets/15555035/9eedd7a2-5cb2-4983-ab0c-aaf71dd5cb29)

These will be released in next patch, a long with other big improvements/corrections for securing connections. Thank you for your feedback and making this safer.

**Comment by undergroundwires** [comment]
Thank you for the clean report and suggestions.

You're right, [Microsoft warns about it](https://learn.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-#tls-protocol-version-support):

> TLS 1.3 is supported starting in Windows 11 and Windows Server 2022. Enabling TLS 1.3 on earlier versions of Windows is not a safe system configuration.

TLS 1.3 will no longer be enabled on versions before Windows 11. Even the current version the script is running is Windows 10 and earlier, the script will refuse to complete:

![image](https://github.com/undergroundwires/privacy.sexy/assets/15555035/9a12de3b-3473-4f88-9011-e26078093847)

DTLS 1.3 seems to have [never been supported by Microsoft](https://learn.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-#tls-protocol-version-support). It was simply a bug to have it. It's changed to DTLS 1.2. and the script will refuse to run versions before 1607.

![image](https://github.com/undergroundwires/privacy.sexy/assets/15555035/9eedd7a2-5cb2-4983-ab0c-aaf71dd5cb29)

These will be released in next patch, a long with other big improvements/corrections for securing connections. Thank you for your feedback and making privacy.sexy safer for all of us.

**Comment by undergroundwires** [comment]
I've reworked network-related scripts completely in [0.13.3](https://github.com/undergroundwires/privacy.sexy/releases/edit/0.13.3), it should solve this issue along with others.

privacy.sexy does have operating system checks now and does not enable these protocols on unsupported versions  so TLS 1.3 is now only enabled for Windows 11 and above.

**Comment by undergroundwires** [comment]
I've reworked network-related scripts completely in [0.13.3](https://github.com/undergroundwires/privacy.sexy/releases/edit/0.13.3), it should solve this issue along with others.

privacy.sexy does have operating system checks now and does not enable these protocols on unsupported versions  so TLS 1.3 is now only enabled for Windows 11 and above. A warning is also added.
