### ISSUE TITLE
[BUG]: standard version of script did sg cos i can't open/use Free Tube anymore

### ISSUE THREAD

**Issue by Nufi0** [undergroundwires/privacy.sexy#183]
standard version of script did sg cos i can't open/use Free Tube anymore

what settings shuld i revert exactly? cos logicaly not everythings needs to be reverted in the script for me

**Comment by Fnoberz** [comment]
I recommend you to Backup Restore before starting scripts because sometimes It may disable the ability to back up your data.

**Comment by MiRw3b** [comment]
try reverting the changes made on cryptography and revert the "disable SMBV1 protocol", potentially a fix

**Comment by undergroundwires** [comment]
I've reworked network-related scripts completely in [0.13.3](https://github.com/undergroundwires/privacy.sexy/releases/edit/0.13.3), it should solve this issue along with others.
