### ISSUE TITLE
[BUG]: Online games login broken & Some apps (Firewall)

### ISSUE THREAD

**Issue by MiRw3b** [undergroundwires/privacy.sexy#185]
So, i used privacy.sexy on 2 custom iso's (AtlasOS and DuckOS).
And by using the windows defender disable, it somehow broke some online games like osu!lazer (can't login), but not all of them.

This issue wasn't there before using privacy.sexy, so i reverted some changes of the firewall services (both user and kernel) (script below)
then restarted, but the issue is still here. 

Here's below both the revert script config i used and the original config i used to tweak :
[the scripts mir used.zip](https://github.com/undergroundwires/privacy.sexy/files/10202886/the.scripts.mir.used.zip)

**Comment by MiRw3b** [comment]
i tried reverting even further, still not working. tried reinstalling/enabling all the protocols that were disabled including smb v1, also tried removing the drm restriction. still not working.
i desesperatly need help coz 💀 i dont wanna reinstall windows over and over ye

**Comment by MiRw3b** [comment]
Welp, i think i found the cause of it, it might be that those games and apps doesn't support TLS and DTLS 1.3
=> revert cryptography on iss changes & re-enable SMBV1 protocol 
Might be the fix, so uh; i guess you should put notices on it as it seems like it breaks things up.

**Comment by redraskal** [comment]
Were you able to actually enable the firewall service after reverting? I can't start the Firewall service anymore after disabling and reverting because mpsdrv won't start.

**Comment by undergroundwires** [comment]
The fix is released since [0.13.3](https://github.com/undergroundwires/privacy.sexy/releases/edit/0.13.3) 🎉.

I've reworked network-related scripts completely in [0.13.3](https://github.com/undergroundwires/privacy.sexy/releases/edit/0.13.3), it should solve this issue along with others.
