### ISSUE TITLE
Disabling Windows Defender, but *excluding* firewall, still breaks Windows Firewall... [see screenshots]

### ISSUE THREAD

**Issue by DiscoFever78** [undergroundwires/privacy.sexy#193]
Please see screenshots:

![firewall-error](https://user-images.githubusercontent.com/67702582/211650048-6a43a875-854c-44ea-9711-c5d57aadcd25.jpg)
![privacy-is-sexy_disable-defender_not-firewall](https://user-images.githubusercontent.com/67702582/211650082-d2095d36-9c55-4323-ac97-cdf46a32b220.jpg)

Are there any checkbox items to uncheck to keep Windows Firewall working? Thanks, and my apologies if this has been asked before.

**Comment by Oxi-nya** [comment]
![image](https://user-images.githubusercontent.com/87499654/212541949-cda9797d-40da-4d95-97ff-81306b40cd76.png)

**Comment by Oxi-nya** [comment]
also this
![image](https://user-images.githubusercontent.com/87499654/212542860-9e7401cb-c4dd-48a2-aa4d-ed24e2b6bf96.png)

**Comment by he3als** [comment]
https://github.com/undergroundwires/privacy.sexy/pull/201

**Comment by Mark-Joy** [comment]
@he3als Please also move "Hide Firewall and network protection" into "Windows Firewall" section.
Currently it is in: Disable Windows Defender -> Disable Defender Features -> Remove Defender From UI -> Hide the "Firewall and network protection" area

**Comment by undergroundwires** [comment]
Hi @Mark-Joy, could you elaborate why? What is it solving? As you see `Hide areas in Windows Defender Security Center` (its parent category) is a big category with a lot of similar stuff, why would we break the group and change the consistency?

**Comment by undergroundwires** [comment]
This is fixed since [0.12.1](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.1).
