### ISSUE TITLE
[BUG]: Uninstalling the SecHealthUI fails, despite the app being installed.

### ISSUE THREAD

**Issue by haiku-balls** [undergroundwires/privacy.sexy#195]
### Description

When toggling the Uninstall Windows Store Apps > Uninstall Sys. Apps > People Hub > Windows Security GUI (Sec Health UI) App, it reports 'Not Installed' despite the app being there. The reason is the app isn't "Microsoft.Windows.SecHealthUI" it's "Microsoft.SecHealthUI". I'm not entirely sure if it's due to me using a development build.
![image](https://user-images.githubusercontent.com/65756037/213582683-b855046e-79ce-45fc-a19b-402157f81f03.png)
![image](https://user-images.githubusercontent.com/65756037/213582436-82bb121c-0d16-4fde-a4a3-192a25356576.png)

### OS
Windows 22H2 (Build 25276.1; Dev)

### Reproduction steps
Toggle the option. Run the script with that option, reports 'not installed'.

### Scripts

```
@echo off
:: https://privacy.sexy — v0.11.4 — Thu, 19 Jan 2023 22:59:05 GMT
:: Ensure admin privileges
fltmc >nul 2>&1 || (
    echo Administrator privileges are required.
    PowerShell Start -Verb RunAs '%0' 2> nul || (
        echo Right-click on the script and select "Run as administrator".
        pause & exit 1
    )
    exit 0
)


:: ----------------------------------------------------------
:: ---------Windows Security GUI (Sec Health UI) app---------
:: ----------------------------------------------------------
echo --- Windows Security GUI (Sec Health UI) app
PowerShell -ExecutionPolicy Unrestricted -Command "$package = Get-AppxPackage -AllUsers 'Microsoft.Windows.SecHealthUI'; if (!$package) {; Write-Host 'Not installed'; exit 0; }; $directories = @($package.InstallLocation, "^""$env:LOCALAPPDATA\Packages\$($package.PackageFamilyName)"^""); foreach($dir in $directories) {; if ( !$dir -Or !(Test-Path "^""$dir"^"") ) { continue }; cmd /c ('takeown /f "^""' + $dir + '"^"" /r /d y 1> nul'); if($LASTEXITCODE) { throw 'Failed to take ownership' }; cmd /c ('icacls "^""' + $dir + '"^"" /grant administrators:F /t 1> nul'); if($LASTEXITCODE) { throw 'Failed to take ownership' }; $files = Get-ChildItem -File -Path $dir -Recurse -Force; foreach($file in $files) {; if($file.Name.EndsWith('.OLD')) { continue }; $newName =  $file.FullName + '.OLD'; Write-Host "^""Rename '$($file.FullName)' to '$newName'"^""; Move-Item -LiteralPath "^""$($file.FullName)"^"" -Destination "^""$newName"^"" -Force; }; }"
:: ----------------------------------------------------------


pause
exit /b 0

```

**Comment by undergroundwires** [comment]
Hi @haiku-balls,thank you for the quality issue with all context and good suggestion. I will fix this in a patch release soon.

I looked for official sources and did tests to see these service statuses.

Here are my results:

| Service Name | Sources from Microsoft | Existence (Windows 10 21H2) | Existence (Windows 11 21H2) |
| -------------------- | ---------------------------------- | ------------------------------------------- | ------------------------------------------ |
| `Microsoft.Windows.SecHealthUI` | [Services CSV file microsoft.com](https://download.microsoft.com/download/e/1/0/e10a6884-2e7a-4d80-ac2f-884c39a2a1b2/5001337.csv) | ✅ Exists | ❌ Missing |
| `Microsoft.SecHealthUI` | [Windows Security Update - Microsoft Support](https://support.microsoft.com/en-us/topic/windows-security-update-a6ac7d2e-b1bf-44c0-a028-41720a242da3) | ❌ Missing | ✅ Exists |

So `Microsoft.SecHealthUI` seems to be Windows 11 equivalent of the `Microsoft.Windows.SecHealthUI`.

As we have official documentation for both services, the script should attempt to uninstall both services with some special logic:

- Delete `Microsoft.SecHealthUI` on Windows 11 only.
- Delete `Microsoft.Windows.SecHealthUI` on Windows 10 only.

**Comment by undergroundwires** [comment]
Windows 11 app removal is added in [0.12.9](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.9) 🚀
