### ISSUE TITLE
[BUG]: Password is asking for almost everything, for exemple open task manager, how to desable it?

### ISSUE THREAD

**Issue by johanplima** [undergroundwires/privacy.sexy#202]
Would love to know how to disable this function, kinda bad and annoying.

**Comment by Abyssgrowth** [comment]
copy this code in powershell or cmd, no password will be needed. (better to have password always, its a strong protection against viruses and malware.)

rem =================================== Windows Policies ===================================
rem --------------------------------- User Account Control ---------------------------------

rem 0 - Elevate without prompting / 1 - Prompt for credentials on the secure desktop / 2 - Prompt for consent on the secure desktop / 3 - Prompt for credentials / 4 - Prompt for consent / 5 (Default) - Prompt for consent for non-Windows binaries
reg add "HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System" /v "ConsentPromptBehaviorAdmin" /t REG_DWORD /d "5" /f

rem 0 - Automatically deny elevation requests / 1 - Prompt for credentials on the secure desktop / 3 (Default) - Prompt for credentials
reg add "HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System" /v "ConsentPromptBehaviorUser" /t REG_DWORD /d "3" /f

**Comment by Abyssgrowth** [comment]
to activate password use:


rem =================================== Windows Policies ===================================
rem --------------------------------- User Account Control ---------------------------------

rem 0 - Elevate without prompting / 1 - Prompt for credentials on the secure desktop / 2 - Prompt for consent on the secure desktop / 3 - Prompt for credentials / 4 - Prompt for consent / 5 (Default) - Prompt for consent for non-Windows binaries
reg add "HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System" /v "ConsentPromptBehaviorAdmin" /t REG_DWORD /d "1" /f

rem 0 - Automatically deny elevation requests / 1 - Prompt for credentials on the secure desktop / 3 (Default) - Prompt for credentials
reg add "HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System" /v "ConsentPromptBehaviorUser" /t REG_DWORD /d "0" /f

**Comment by undergroundwires** [comment]
I'm not sure how this contributes to improving privacy in any way.
