### ISSUE TITLE
[BUG]: Removed Camera not revertable

### ISSUE THREAD

**Issue by BurningAlmonds** [undergroundwires/privacy.sexy#206]
### Description
I used the scripted, and i must have misclicked because it also disabled the camera for all apps(i think) and when i use the reverted version of it and run it it still doesnt work. If I try to change it manually, it says i dont have permission to change it because my device is managed by some organization and i cant get this oragnization stuff away by using the group policy editor.
Im not very experienced in Windumb(I switched to it a year ago, because my school requires me to use Microsoft-products and i was too stupid to just use a vm), and i might have done something wrong.

### Reproduction steps
-Run the Camera remove
-try to revert it
-see that it doesnt work

### Expected behavior
I cant use my camera even though i reverted the thing

### Distribution
   - Web (on Desktop)

**Comment by undergroundwires** [comment]
Hi, sorry for the late response. privacy.sexy does all of these when you revert  `Deny app access to microphone` and more. I'm not sure what you mean by "Camera remove". It's very useful providing script files so we can check exactly what has happened.

There are many scripts related to Camera, maybe you reverted uninstallation of Windows Camera app which was not the case here.

Reverting deny app access should work without any issues.

**Comment by undergroundwires** [comment]
@BurningAlmonds, if you're still around, how did you realize that you could not use your camera? Which app were you using? This would be helpful to highlight in documentation to warn other users.
