### ISSUE TITLE
[Feature] On/off toggle for tweaks

### ISSUE THREAD

**Issue by undergroundwires** [undergroundwires/privacy.sexy#21]
- [x] Add support in `application.yml`
- [x] Support in the GUI
- [x] Documention, maybe a `CONTRIBUTING.md`
- [x] Reference implementations for some of the scripts

**Comment by Disk2019** [comment]
Awesome Brother Great Going.....

**Comment by undergroundwires** [comment]
This is now live with [0.5.0 release](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.5.0) 🎉

It's done simply by adding `revertCode` parameter in existing  scripts. It's done by editing [`application.yaml`](https://github.com/undergroundwires/privacy.sexy/blob/master/src/application/application.yaml) as documented in [`README.md`](https://github.com/undergroundwires/privacy.sexy/blob/0.5.0/README.md#extend-scripts), tests and [`CONTRIBUTING.MD`](https://github.com/undergroundwires/privacy.sexy/blob/0.5.0/CONTRIBUTING.md#extend-scripts).

I added reverting functionality to some scripts. Examples: [single line](https://github.com/undergroundwires/privacy.sexy/blob/0.5.0/src/application/application.yaml#L324), [multiline](https://github.com/undergroundwires/privacy.sexy/blob/0.5.0/src/application/application.yaml#L350). Community help is wanted to add making other scripts revertable 🙏🏿. And feel free give to give feedback on how it looks and if we can improve it 😀

@ghost, sad that you have become a ghost. You'll always be remembered by me and the git history. Thanks for all of your ideas and contributions. I'm sure you'll have a very bright future in front of you. Keep it cool my friend.

**Comment by GentleRock** [comment]
> It's done simply by adding `revertCode` parameter in existing scripts

Hello,

*)
I was trying to **figure out from the windows.yaml and other ts files how a script is marked with the revert button, i.e. is reversible**

I've read the file collection-files.md which I only partly understand at this moment

For example, the script
   Configure programs > Disable Visual Studio data collection > Disable participation in Visual Studio Customer Experience Improvement Program (VSCEIP)

**it is not marked with 'revertCode'

and yet it has an enabled button 'Revert'**

Should I maybe find (but how?) the function 'SetRegistryValue'
and see if it is marked with 'revertCode'

and do for all the functions or calls in it and see if they are all marked with the 'revertCode' flag?
If so, is there a .ts code doing this?



*)
Separately, I'd also ask, what does the '**triangle-exclamation**' means? I guess, that there's soemthing I need to be very careul about!
but how do I find out from the windows.xaml file if a script has that triangle enable?


I'm on Windows desktop.

Thank you for all you work, it's being much helpful!

Marcello
(I have been writing in the past here as Marcello Pietrobon)
