### ISSUE TITLE
[BUG]: configure browsers/configure edge/disable recent apps (revert) bug

### ISSUE THREAD

**Issue by msoltyspl** [undergroundwires/privacy.sexy#211]
### Description

This small script is missing whitespace between `0` and `/`, causing the revert variant to fail

### OS

Win 11 22H2

### Reproduction steps

Try to revert.

### Scripts

```
echo --- Disable recent apps (revert)
reg add "HKCU\Software\Policies\Microsoft\Windows\EdgeUI" /v "DisableRecentApps" /t REG_DWORD /d 0/f
```

**Comment by undergroundwires** [comment]
Fix is released in [0.12.3](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.3).
