### ISSUE TITLE
group policy in windows rather than reg keys?

### ISSUE THREAD

**Issue by lepras** [undergroundwires/privacy.sexy#212]
### Description

Registration keys are often changed after updates and things get reverted, isn't using group policies far better way?

### Proposed solution

https://stackoverflow.com/questions/39834069/how-to-change-group-policy-via-command-line

**Comment by undergroundwires** [comment]
Thank you for your contribution, @lepras. Your insights are valued.

Two points:

- Setting registry keys sets group policies, it's a way of doing it. So both registry and CLI methods sets the group policies.
- I see that the CLIs mentioned provided depends also on registry keys, i.e. same metadata.

I agree that it would better to use a way that does not depend on modifying registry directly.

Is there any code snippet using a CLI that exists in OS by default (can be PowerShell module too) that can do this simpler without registry keys?

**Comment by lepras** [comment]
https://learn.microsoft.com/en-us/powershell/module/grouppolicy/

**Comment by undergroundwires** [comment]
[`Set-GPRegistryValue`](https://learn.microsoft.com/en-us/powershell/module/grouppolicy/set-gpregistryvalue) requires the same registry values, I don't see the added value. It modifies registry in same way.

**Comment by lepras** [comment]
Oh so setting registry values and group policies are the same thing?

If yes, then please close this issue and thanks for the valuable tool!

**Comment by undergroundwires** [comment]
Thank you for the nice comment ❤️

This is what I understand from documentation. If it was wrong we can re-open this and take a look at it, I agree that using a more "managed" approach than low-level registry keys would be better.
