### ISSUE TITLE
How to export single-page HTML?

### ISSUE THREAD

**Issue by jackjr79** [undergroundwires/privacy.sexy#220]
Is there any way to save the web site on a single HTML file? So I can run any web-browser offline mode?

**Comment by SnowzNZ** [comment]
You can use privacy.sexy locally, but just not as a *single* html file. There are 2 ways to do this:
1. Get the[ latest desktop app for your operating system](https://github.com/undergroundwires/privacy.sexy/releases)
2. Clone the repo, run `npm install` then `npm run dev`. You can then go to `127.0.0.1:5173` in your web browser.

Hope this helps. If you need any help, let me know 😄

**Comment by undergroundwires** [comment]
You can also run it as docker, [see instructions](https://github.com/undergroundwires/privacy.sexy/blob/0.12.2/docs/development.md#running) but I just realized that the commands are not working anymore. I will fix the Dockerfile in following days.

**Comment by undergroundwires** [comment]
Dockerfile is fixed/updated with automated tests. Closing this issue.
