### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Sekkur** [undergroundwires/privacy.sexy#226]
### Description
I ran a script to mainly disable Windows Defender, and I ran it with all of its sub-options enabled. Now I cannot download any game from Microsoft Store, with the error code: `Code: 0x80073D0A`. Google says this is related to Windows Defender Firewall

### OS
22H2 Windows 10 Pro

### Reproduction steps
* Open Microsoft Store
* Download any app

## Screenshot(s)
![image_2023-04-25_131537628](https://user-images.githubusercontent.com/83727884/234216446-c3be67a9-0853-4ef7-9394-dc5be1682228.png)

**Comment by undergroundwires** [comment]
Hi @Sekkur ,

It's not a bug, it's [known to break Microsoft Store and even documented with same error code](https://github.com/undergroundwires/privacy.sexy/blob/3a594ac7fd708dc1e98155ffb9b21acd4e1fcf2d/src/application/collections/windows.yaml#L4605-L4648). You can revert "Disable Windows Defender Firewall service (breaks Microsoft Store and `netsh advfirewall` CLI)" script to get it working. Be careful with scripts that says "break" on it.

Thanks
