### ISSUE TITLE
Win 7

### ISSUE THREAD

**Issue by harryray33** [undergroundwires/privacy.sexy#231]
Does this work with Win 7?

Thanks

**Comment by undergroundwires** [comment]
Hi @harryray33 .

I have never tested it on Windows 7.

Regarding desktop app, privacy.sexy uses latest version of Electron which [removed support for Windows 7](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice), however the older versions prior to 0.12.0 should run on Windows 7.

Regarding script, there are some minor scripts  specific for Windows 7, some of the scripts that applies to 10 / 8 applies also to 7. However, it's untested and I don't plan to maintain support for Windows 7. But if you have scripts to add, or improve to support 7 please create new issues and I'd accept them.

Thanks.
