### ISSUE TITLE
[BUG]: On website not hide sections that not relate to found phrase

### ISSUE THREAD

**Issue by Drovosek01** [undergroundwires/privacy.sexy#235]
If my memory does not fail me, then when I used the site a couple of weeks ago, when I entered a word in the search, for example, "defender", sections disappeared at the bottom of the rhinestone in which the word was not found and the section in which this word was revealed

Now when I enter the word "defender" in the search bar, nothing happens. If I open sections that don't have this word - there's just a void.

![image](https://github.com/undergroundwires/privacy.sexy/assets/29478700/d16a2be7-b739-4d68-a979-fde04696c985)

![image](https://github.com/undergroundwires/privacy.sexy/assets/29478700/d0f6473a-7168-4781-a154-1141371dac7f)

**Comment by undergroundwires** [comment]
Hi @Drovosek01 , thank you for the bug report.

I see that the search is completely broken somehow. I will patch this right away once I fix #235, it blocks everything else for now. I've modernized some of the stuff in the codebase and looks like I've broken a lot in this patch, sorry for that.

One temporary fix to use **Tree** view before searching before I patch this.

![image](https://github.com/undergroundwires/privacy.sexy/assets/15555035/8cd54d7d-cf4f-4df9-8a87-73a7a9efe7b3)

**Comment by undergroundwires** [comment]
This is now resolved with release of [0.12.2](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.2). Thank you again for the issue and feel free to hang around and create an issue if you have an idea or see something else that's not working.
