### ISSUE TITLE
[BUG]: Update to latest version 0.12.1 fails.

### ISSUE THREAD

**Issue by TheAndr0id** [undergroundwires/privacy.sexy#237]
### Description

New update doesn't download.

### Reproduction steps
Started up the 0.12.0 version of the app, it stated there was an update.  I clicked sure, download that.  It didn't.  
(The window opens, but nothing happens.  Ever.)

### Expected behavior
A download.  An error message.   Something...

### Screenshots
![Capture1](https://github.com/undergroundwires/privacy.sexy/assets/70486840/f497c64a-56e4-428a-b1df-b66e5726f44d)
![Capture2](https://github.com/undergroundwires/privacy.sexy/assets/70486840/78e8cd2f-4670-4e98-8d52-d0d01f06f180)
### Distribution
Windows 10 22H2

### Additional context
Issue with 0.12.0?  With the link?  With the download code?

**Comment by undergroundwires** [comment]
Hi @TheAndr0id , thanks for the bug report.

I can reproduce this. I see that this started happening after my manual workaround for #233. The files in the release page were named in different way. I fixed this manually and it auto-update should work now.

**Comment by undergroundwires** [comment]
It still did not work, however I needed to upload one more file. Now it's working fine. Desktop distributions will get stable again with a patch soon.
