### ISSUE TITLE
How to revert changes from standard select

### ISSUE THREAD

**Issue by DealsBeam** [undergroundwires/privacy.sexy#241]
I got the latest version v0.12.2, selected standard and ran it, however now I would like to revert the changes back, anyway to do so? my windows stopped updating

revert changes are only available on 5 options

**Comment by undergroundwires** [comment]
- Revert all selected: I plan to release in upcoming minor releases as part of #68. Before that you need to manually revert those.
- Some scripts are not reversible and cannot be reversible, like cleanup functions.
- Standard script selection should not interfere with Windows updates, this is a major bug if it's the case, please create another issue for this using [bug template](https://github.com/undergroundwires/privacy.sexy/blob/0.12.2/.github/ISSUE_TEMPLATE/1-bug-report-scripts.md) that would give us the necessary context to reproduce it and fix it, other way we don't have the context to take any action.
