### ISSUE TITLE
Hardentools

### ISSUE THREAD

**Issue by Nordmannn** [undergroundwires/privacy.sexy#253]
Hi undergroundwires,

I've been using "hardentools" for quite a while now.

Here is the link:
https://github.com/securitywithoutborders/hardentools

Maybe it is possible to integrate some of the protecting features in your attempt to protect user from malicious attacks and to increase the privacy protection.

Just a thought . . .
Mike

**Comment by undergroundwires** [comment]
Hi @Nordmannn , thanks for the tips. hardening is part of core privacy.sexy's core functions. So contributions are more than welcome to add more scripts through issues/PRs. However, having single issue for inspecting another project and integrating it is not sustainable, we should go for issue/PR per script requested so we can test them thoroughly and find relevant documentation.

P.S.: I have worked on building extensive Microsoft Office configuration scripts but I want to first implement functionality so these software can be configured across all OSes (usually configured same way on macOS, Linux etc.), then roll out the Office scripts so e.g. Microsoft Word can be configured same way on macOS+Windows.
