### ISSUE TITLE
[BUG]: Wrong registry references

### ISSUE THREAD

**Issue by tempdrive** [undergroundwires/privacy.sexy#255]
Hi,

I have noticed that there are a couple of invalid registry references in v0.12.2 as per the below:

name: **Disable Application Impact Telemetry (AIT)**
recommend: standard
code: reg add "HKLM\Software\Policies\Microsoft\Windows\AppCompat" /v "AITEnable" /t REG_DWORD /d "0" /f
revertCode: **reg add "HKLM\Software\Policies\Microsoft\SQMClient\Windows" /v "CEIPEnable" /t REG_DWORD /d "1" /f**

The **revertCode** part refers to a different registry entry.

name: **Block Anonymous enumeration of SAM accounts**
recommend: standard
docs: https://www.stigviewer.com/stig/windows_10/2019-01-04/finding/V-63745
code: reg add "**HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\kernel**" /v "RestrictAnonymousSAM" /t REG_DWORD /d 1 /f
revertCode: reg add "**HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\kernel**" /v "RestrictAnonymousSAM" /t REG_DWORD /d 0 /f

For the above, the proper path would be "**HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Lsa**", which is also referenced in the link provided.

**Comment by undergroundwires** [comment]
Hi, thank you for the report, CEIP/AIT stuff were fixed at e2b3213b030bdc5cadf853102f1cd26759b215ff along with other improvements but it got stale before merging it. I'll ensure that it will be merged in a patch release.

`RestrictAnonymousSAM` were missed completely. It will be fixed. I'd merge it if someone creates [a PR](https://github.com/undergroundwires/privacy.sexy/blob/master/CONTRIBUTING.md#extend-scripts) for this.

**Comment by undergroundwires** [comment]
"Disable Application Impact Telemetry (AIT)" is fixed and documented, it's now under new category "Disable Application Compatibility Framework" with more scripts added/fixed and documented, it's released in [0.12.5](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.5) 🚀

**Comment by undergroundwires** [comment]
"RestrictAnonymousSAM" is fixed and documented, renamed it from  "Disable anonymous enumeration of SAM accounts" to "Disable unauthorized user account discovery (anonymous SAM enumeration)" for simplicity, it's released in [0.12.9](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.9) 🚀. Thank you for thee feedback @tempdrive again, you are always welcome to report if you see anything else.
