### ISSUE TITLE
[BUG]: Microphone

### ISSUE THREAD

**Issue by Maks3461** [undergroundwires/privacy.sexy#257]
please help what to do if the microphone does not work after that?

**Comment by Nordmannn** [comment]
Hello Maks3461,
open your browser, clear cache, visit this site (https://privacy.sexy/) again, open the "Disable OS Data Collection" Section, open "Deny app access to personal information", choose **revert** on "Deny app access to microphone", download that script, execute it and done. Your microphone should work again unless . . . . there is another problem  :-)

**Comment by undergroundwires** [comment]
Please provide the provided script along with [requested information](https://raw.githubusercontent.com/undergroundwires/privacy.sexy/0.12.3/.github/ISSUE_TEMPLATE/1-bug-report-scripts.md) to allow us to reproduce this.

**Comment by Maks3461** [comment]
Thanks!
