### ISSUE TITLE
Windows etc. tweaks collection

### ISSUE THREAD

**Issue by Tu-sketch** [undergroundwires/privacy.sexy#258]
Over the years I have collected many tweaks along the way. Altough they are not in a "script" they can be executed manually.  It is possible that privacy.sexy has already included most of them. Still its wortwhile to take a look at them. Hope this is in some way useful.

Have fun.
Mike

[AttackSurfaceReduction.txt](https://github.com/undergroundwires/privacy.sexy/files/12648318/AttackSurfaceReduction.txt)
[Firewall.txt](https://github.com/undergroundwires/privacy.sexy/files/12648319/Firewall.txt)
[Office optimieren.txt](https://github.com/undergroundwires/privacy.sexy/files/12648320/Office.optimieren.txt)
[Tuning.txt](https://github.com/undergroundwires/privacy.sexy/files/12648321/Tuning.txt)
[Windows 10 optimieren.txt](https://github.com/undergroundwires/privacy.sexy/files/12648322/Windows.10.optimieren.txt)
[Windows 10 optimieren.reg.txt](https://github.com/undergroundwires/privacy.sexy/files/12648342/Windows.10.optimieren.reg.txt)
[Chrome optimieren.reg.txt](https://github.com/undergroundwires/privacy.sexy/files/12648345/Chrome.optimieren.reg.txt)

**Comment by undergroundwires** [comment]
Hi Mike, happy to see you here again, and thank you for the sharing your collection with us. I've checked them all and see that there are many things that privacy.sexy already does not have but I'd like to them here, especially attack surface reduction. `Firewall.txt` should have reference documentation as evidence showing these processes might have network connections.

It's too hard to track down addition of everything in single GitHub issue. We should create issues or PRs for each script or category to be able to manage and track the work better.

It takes time to name them, find good documentation and add revert codes and I plan to prioritize other bug fixes/features for a while before focusing on adding more scripts. I'd merge PRs though, the configurations selected are of high quality.

This is good start to add new scripts: [more information about extending scripts](https://github.com/undergroundwires/privacy.sexy/blob/0.12.3/CONTRIBUTING.md#extend-scripts).

**Comment by undergroundwires** [comment]
Linking this to #245 to centralize resources to other script collections.
