### ISSUE TITLE
Clarification: Disable default browser agent reporting (Firefox) [Better description?  More details?]

### ISSUE THREAD

**Issue by TheAndr0id** [undergroundwires/privacy.sexy#259]
This isn't a bug, the scripts are doing everything correctly selected at the right level (standard).  

The issue is it's kind of confusing and I'm wondering if there was a better way to clarify this.

Under Configure Programs - > Configure Browsers -> Configure Mozilla Firefox telemetry

There is the entry of Disable default browser agent reporting.

The issue is it's not very clear what/why it's doing what it's doing.  In this case the initial reason for this Firefox scheduled task is innocent, it is there to ensure that Firefox stays the default browser in Windows (since Microsoft likes to switch it back to Explorer/Edge without asking).  This task runs once a day to set the value, and although it's a hack, it makes sense.  

The problem is someone at Mozilla decided that it should also report what browser the default was set to, and details of your current Firefox installation is back to Mozilla when it runs - even if the default browser is Firefox.  Ugh (/me shakes head).

The registry entry HKLM\SOFTWARE\Policies\Mozilla\Firefox\DisableDefaultBrowserAgent is there to tell new Firefox installs/upgrades not to reinstall the scheduled task.

Now short term maybe adding one (or more) of these links to the information button on this option would be a good start:

- https://firefox-source-docs.mozilla.org/toolkit/mozapps/defaultagent/default-browser-agent/index.html
- https://www.askvg.com/tip-disable-default-browser-agent-after-installing-mozilla-firefox/
- https://www.bleepingcomputer.com/news/software/firefox-now-tells-mozilla-what-your-default-browser-is-every-day/

(These were just the first few Google hits that made sense to me)

A bigger question/suggestion might be how to include comments/popup/info section for each option/section to better explain why this is "a thing".  It wouldn't have to be a change to the UI per say, maybe just add extra comments into the generated script with a short description?

Maybe a more "scary" description of the item?  The description didn't look bad and I didn't see it as bad.  Kind of a "Lock the front door" when it should read "Lock the front door to keep axe murder outside"...

Then again, it could just be me not reading correctly.  It happens.... 😄

**Comment by undergroundwires** [comment]
Thank you @TheAndr0id, I will add the documentation according to your feedback and share here for feedback before releasing in a patch.

**Comment by undergroundwires** [comment]
Thank you @TheAndr0id for another quality feedback, I agree with your points and the links are very helpful. I will add the documentation according to your feedback and share here for feedback before releasing in a patch.

**Comment by undergroundwires** [comment]
I thought some time to look at this.

Flattened scripts under `Configure Firefox` for simplicity, renamed them for clarity and added brief documentation that's mainly based on the first link you shared.

<details>
  <summary>Review the new names/documentation</summary>
  
![image](https://github.com/undergroundwires/privacy.sexy/assets/15555035/2521f700-4dbc-48b2-b711-58b8b4a07161)
  
</details>

Does it look good? Or should we do something else/more @TheAndr0id ?

**Comment by undergroundwires** [comment]
I thought some time to look at this.

Flattened scripts under `Configure Firefox` for simplicity, renamed them for clarity and added brief documentation that's mainly based on the first link you shared.

<details>
  <summary><strong>Expand to review the new names/documentation</strong></summary>
  
![image](https://github.com/undergroundwires/privacy.sexy/assets/15555035/2521f700-4dbc-48b2-b711-58b8b4a07161)
  
</details>

Does it look good? Or should we do something else/more @TheAndr0id ?

**Comment by TheAndr0id** [comment]
That looks great!  Thank you!

**Comment by undergroundwires** [comment]
Released as part of [0.13.5](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.5) 🚀.
