### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by GiveMeFox** [undergroundwires/privacy.sexy#268]
### Description

after choosing some options and running the script after restarting my pc windows started to be laggy when trying to move them and also theres like 15 more processes that started to run in task manager then before i run the script

### Reproduction steps

[privacy-sexy.txt](https://github.com/undergroundwires/privacy.sexy/files/12832231/privacy-sexy.txt)

### Distribution

web

### Additional context

is there a way to upload this script to privacy.sexy and just click revert on everything?

**Comment by undergroundwires** [comment]
Hi,
To answer your question, there's no support for it.
You can track the progress at #59 and #68.
About new processes, I'm not sure what they are, without more context it's impossible to reproduce or fix.

**Comment by GiveMeFox** [comment]
i attached the script

**Comment by undergroundwires** [comment]
What processes started running in task manager that were not running before? It needs to be more specific and reproducible so we can verify and solve.
