### ISSUE TITLE
Major Part of M$ Telemetry Removal is to Remove All Hidden Scheduled Tasks at Every Boot as they Appear Again n Again on Every Boot.

### ISSUE THREAD

**Issue by Disk2019** [undergroundwires/privacy.sexy#27]
This is a Reg Tweak . It Does not Work if we convert it to batch to be taken under privacy.sexy script hence i am providing it here as extra. save it as RemoveHiddenScheduledTasks.reg & use it with any program to run it at every boot with prompt.

Windows Registry Editor Version 5.00

[-HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tasks]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tree]
"SD"=hex:01,00,04,94,c4,00,00,00,d0,00,00,00,00,00,00,00,14,00,00,00,02,00,b0,\
  00,08,00,00,00,00,02,18,00,ff,01,1f,00,01,02,00,00,00,00,00,05,20,00,00,00,\
  20,02,00,00,00,01,18,00,9f,01,1f,00,01,02,00,00,00,00,00,05,20,00,00,00,20,\
  02,00,00,00,02,14,00,ff,01,1f,00,01,01,00,00,00,00,00,05,12,00,00,00,00,01,\
  14,00,9f,01,1f,00,01,01,00,00,00,00,00,05,12,00,00,00,00,02,14,00,16,01,12,\
  00,01,01,00,00,00,00,00,05,0b,00,00,00,00,02,14,00,16,01,12,00,01,01,00,00,\
  00,00,00,05,14,00,00,00,00,02,14,00,16,01,12,00,01,01,00,00,00,00,00,05,13,\
  00,00,00,00,0b,14,00,ff,01,1f,00,01,01,00,00,00,00,00,03,00,00,00,00,01,01,\
  00,00,00,00,00,05,12,00,00,00,01,01,00,00,00,00,00,05,12,00,00,00

**Comment by undergroundwires** [comment]
Thanks!

I don't understand what the last key adds but as I see the reg file deletes **all of the scheduled tasks**. It looks a bit dangerous as it might include scheduled tasks that privacy-friendly users need as well. It's also important to understand the hex binary in the end which I have no idea what it does.

How about just deleting those tasks that keep coming back instead of all of them? Do you have a list of them so we can look how we can fight them individually?

**Comment by Disk2019** [comment]
that last SD reg value is just to maintain task cache tree so that if a user go to task scheduler manually via my computer manage then it wont result in any error & show him / her blank task scheduler cache only.

if we dont apply this SD value then task scheduler wil result in error if user go to it in manual way till machine restart.
depends upon user if he or she dont want to apply SD value then he or she can just apply delete task scheduler reg key ie :

Windows Registry Editor Version 5.00

[-HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule]

in this scenario user have to restart the machine for task cache tree to be back again as SD value. 
I hope brother u understand it  well after my explanation.

**Comment by undergroundwires** [comment]
Awesome, thanks, crystal clear now. Might add it in "Advanced Settings". [This guy](https://msfn.org/board/topic/176193-scheduled-tasks-eliminating-most-is-a-good-thing/?tab=comments#comment-1133664) adds more binary to different trees. Do you think that they are needed? And do you know where they are coming from? I could not find any official or serious documentation about them.

**Comment by Disk2019** [comment]
That Guy Noel.C has a Great Knowledge.  he is extra marvelous. He has some excellent work before too on his project : Win10 Re tweaker [ https://win10epicfail.proboards.com/thread/100/interested-participating-tweaker-development-test ]
Brother as its your project you are free to do anything i am only a request maker & nothing else to make your project more n more user friendly .
Please again i repeat do not show my name anywhere on project or else my Department team if they come to know again about it will again ban me from using github account & account will again be converted into ghost & that will be second warning for me from my dept as first has been given before & third will be order from a Commission Enquiry been set up for me ====> Result = [ Out of Order ] as Out of Order means Out of Department.

Thanks & Regards
Disk2019

**Comment by Disk2019** [comment]
Yes he is absolutely correct as that msftmonitor task is needed for ctfmon to work properly associated with tabletinputservice.
major role of this task is to maintain ctfmon running in background for win10 UI settings apps to work properly with hardware keyboard .
