### ISSUE TITLE
[FEATURE] - Ability to load pre-generated .bat script to get previous selections

### ISSUE THREAD

**Issue by g-kon** [undergroundwires/privacy.sexy#271]
### Problem description

Hi. First of all thanks for all the great work, truly appreciated. I've just started using privacy.sexy as I had to go through re-formatting my Windows setup and realised that there's a feature which if implemented could make ease of use 10x better for the user. I am aware that there are already presets available, I'm referring to: "Standard", "Strict" and "All". However, I think that if as a user I was able to make my own selections, download the batch script, and then be able to re-visit privacy.sexy with no options selected but instead have a "Load" button where I could use the previously generated batch script to get all MY selections back that would be pretty amazing and would make re-usability a lot faster. To solve this on my own I had to use the software "Greenshot" (a screenshot snipping software) after expanding all the selections I made to manually take screenshots of my selections, and then if I had to generate the script again (e.g. because something was messed up because due to my selections and had to start removing some), I had to go through the screenshots one by one and manually re-select things. That's too tidious in my opinion and could be solved by the feature suggestion I just made.

**Comment by undergroundwires** [comment]
Hi g-kon, thank you for the nice words and your feedback. This was raised in #59. I will look at it after #262. I'd like to prioritize this but I prioritize stability over new features so a lot of effort is going into improving the scripts, their side-effects etc.
