### ISSUE TITLE
[BUG]: Middle mouse button not working on Chromium browsers on Win 10

### ISSUE THREAD

**Issue by asterriya** [undergroundwires/privacy.sexy#275]
[privacy-script.txt](https://github.com/undergroundwires/privacy.sexy/files/13033898/privacy-script.txt)
Applied this script from official site and my middle mouse button stopped working. So now I can't close tab on Chromium based browser at all.

**Comment by undergroundwires** [comment]
Hi.
- Which OS version?
- Which browser?

**Comment by undergroundwires** [comment]
I cannot reproduce this. Tested on W10 22H2 with Google Chrome installed using same script. Tested after and before restart. Most likely not related to privacy.sexy.

**Comment by asterriya** [comment]
Hmm. Looks strange.
