### ISSUE TITLE
[BUG]: Can't sign into Phone Link

### ISSUE THREAD

**Issue by Retrospectre1** [undergroundwires/privacy.sexy#276]
### Description

I'm trying to sign in to Phone Link with my Microsoft account. When I click the button to "Sign in with Microsoft", nothing actually happens. When I signed into Windows with my Microsoft account, a small window came up to allow me to do so, so I expected a similar thing to happen here.
I believe I originally ran the Strict preset of privacy.sexy, but in my attempts to fix the issue, I've run all the revert scripts for MS Edge and Phone Link I could find. I still can't open Edge despite it being a blank app in my start menu (I suspected Phone Link might've been trying to open an Edge window).

### OS

Windows 11 Pro 12H2 build 22000.2538

### Reproduction steps

Open Phone Link
Click Android
Click Sign in with Microsoft

### Screenshots

![PhoneExperienceHost_NOCQ0UF73K](https://github.com/undergroundwires/privacy.sexy/assets/61394613/369abca6-69f2-4968-8f2f-05489079378a)

**Comment by undergroundwires** [comment]
Hi @Retrospectre1 , search for the keyword `breaks` and revert them all. I guess this can be `Disable "Microsoft Account Sign-in Assistant" service`.
