### ISSUE TITLE
Missing Double Quotes in Script - Script Crash [BUG]: 

### ISSUE THREAD

**Issue by ComputerCrack** [undergroundwires/privacy.sexy#277]
In "Disable "Windows Defender Advanced Threat Protection Service" service are 2 instances of file locations without double quotes (last 2 echo commands). Missing this causes the script to crash.
I used the newest windows version.

**Comment by undergroundwires** [comment]
[0.12.6](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.6) is released now 🚀 It should resolve the issue.

**Comment by undergroundwires** [comment]
Closing this, let me know if you see any issues
