### ISSUE TITLE
"Configure Defender" section is under "Disable Visual Studio data collection" 🤔

### ISSUE THREAD

**Issue by Fs00** [undergroundwires/privacy.sexy#28]
Just noticed a little issue:
![Wrong category](https://user-images.githubusercontent.com/30041551/91665701-e3545d00-eaf7-11ea-879f-39a70711dd2d.png)

Probably that _"Configure Windows Defender"_ wasn't meant to be under _"Disable Visual Studio data collection"_ 😜

**Comment by undergroundwires** [comment]
Hi @Fs00 👋 Thanks! Nice observation. Dunno how the f^$k it ended up there haha.

**Comment by undergroundwires** [comment]
Thanks again, fix is on production with [0.7.0](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.7.0), release 🌟

**Comment by Fs00** [comment]
Great! I think this can now be closed.
