### ISSUE TITLE
[BUG]: Removing "Get Help" breaks internet troubleshooting

### ISSUE THREAD

**Issue by ScribbleGhost** [undergroundwires/privacy.sexy#280]
### Description

Removing "Get Help" breaks internet troubleshooting. This is not really a bug, but I think the script generator should make it clear that this will break the troubleshooting.

### OS

Windows 11 23H2

### Reproduction steps

1. Right click on the internet icon in the tray icons.
2. Click on "Diagnose network problems"
3. Instead of troubleshooting you get a message saying "Your PC doesn't have an app that can open this link..."

### Scripts

```
:: ----------------------------------------------------------
:: ------------------Remove "Get Help" app-------------------
:: ----------------------------------------------------------
echo --- Remove "Get Help" app
:: Uninstall 'Microsoft.GetHelp' Microsoft Store app.
PowerShell -ExecutionPolicy Unrestricted -Command "Get-AppxPackage 'Microsoft.GetHelp' | Remove-AppxPackage"
:: Mark 'Microsoft.GetHelp' as deprovisioned to block reinstall during Windows updates.
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.GetHelp_8wekyb3d8bbwe" /f
:: -----------------
```

### Screenshots

![Windows 11 x64-2023-11-06-10-48-28](https://github.com/undergroundwires/privacy.sexy/assets/49068170/5a409791-6d01-4f2e-8563-d2e98672b191)

![Windows 11 x64-2023-11-06-10-42-37](https://github.com/undergroundwires/privacy.sexy/assets/49068170/5cf3656d-9ab9-4339-a3ea-e3a053dbb3ac)

**Comment by undergroundwires** [comment]
I can reproduce this. Thank you for the report and contributing back to/informing the community.

How about renaming script to `Remove "Get Help" app (breaks built-in troubleshooting)`, and this is what I prepared as enhanced docs:

![image](https://github.com/undergroundwires/privacy.sexy/assets/15555035/23c251f2-e6a3-4169-91bc-9467750788ca)

Btw your W11 looks like W10 :)

**Comment by ScribbleGhost** [comment]
Sure, I think that would suffice.

> Btw your W11 looks like W10 :)

Yeah, I am debloating W11 like a madman over here. 😂

**Comment by undergroundwires** [comment]
Release in [0.12.9](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.9)  🚀
