### ISSUE TITLE
Improve robustness for initially elevating script privileges

### ISSUE THREAD

**Issue by MilesFarber** [undergroundwires/privacy.sexy#285]
### OS

Windows

### Name

Automatically run privacy.sexy as admin without user intervention

### Script code

Previously, the script prompted the user to run as admin if it doesn't detect admin.

```
fltmc >nul 2>&1 || (
    echo Administrator privileges are required.
    PowerShell Start -Verb RunAs '%0' 2> nul || (
        echo Right-click on the script and select "Run as administrator".
        pause & exit 1
    )
    exit 0
)
```

This script automatically restarts the script as admin without asking the user to do anything.

```
Set-ExecutionPolicy Unrestricted -Scope CurrentUser
$CurrentUser = New-Object Security.Principal.WindowsPrincipal $([Security.Principal.WindowsIdentity]::GetCurrent())
if($CurrentUser.IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator))
{
  Write-Output "i like ya cut g"
}
else
{
  Write-Output "Running PowerShell Elevated."
  $ElevatedProcess = New-Object System.Diagnostics.ProcessStartInfo "PowerShell";
  $ElevatedProcess.Arguments = "& '" + $script:MyInvocation.MyCommand.Path + "'"
  $ElevatedProcess.Verb = "runas"
  [System.Diagnostics.Process]::Start($ElevatedProcess)
  Exit
}
```

Big problem: It's Powershell and i don't know if it works with .cmd files.

### Suggested recommendation level

STANDARD

### Additional documentation/references

https://github.com/MilesFarber/Windows10SuperCharger Example ps1 file that uses this. RUN IN A VIRTUAL MACHINE

**Comment by undergroundwires** [comment]
Hi @MilesFarber, thanks for the report and recommendation in your project. It's appreciated <3.

The existing code should already run the process automatically as administrator if admin is not detected.

If we look at this line:

```batchfile
PowerShell Start -Verb RunAs '%0' 2> nul
```

`%0` is the script path. Single quotes are used to handle paths with spaces included. `-Verb RunAs` prompts for administrator privileges.

Did this not work for you? In that case what was the full absolute path of the script you were executing? You can also remove `2> nul` and re-run the script to see what was causing the error.

We run today a lot of powershell scripts, but need to inline them to be able to properly execute them using `cmd` (batchfile).  This makes the code harder to read. This can be acceptable for individual scripts but preferable to keep the global code as readable as possible (i.e. batchfile). The reason to use batchfile is that they're simple to execute without being affected by execution policies of the host operating system. This makes the generated scripts more accessible and easier to execute by many.

**Comment by MilesFarber** [comment]
When i tried to run it it said "Right-click on the script and select "Run as administrator"." Then "Press any key to continue..." but now i cannot reproduce it anymore akdfjlghspfhmbfh ANGY

**Comment by undergroundwires** [comment]
😃 It can be due to some naming in the path.

PowerShell solution is well-written, and much more robust than this "clever" (hacky) way.

It also allows exiting with same exit code as the previous running process, showing proper error messages etc.

But I'm thinking from the users perspective, would people appreciate more robust approach here with the values given, or readable?

Because right know it's pretty simple to read and follow, but it will get ugly with inlined powershell. 

For example, following code is inlined powershell for deleting directory contents (look at how ugly it is):

```ps1
:: Clear directory contents  : "%LOCALAPPDATA%\Microsoft\Windows\INetCache\IE"
PowerShell -ExecutionPolicy Unrestricted -Command "$pathGlobPattern = "^""$($directoryGlob = '%LOCALAPPDATA%\Microsoft\Windows\INetCache\IE'; if ($directoryGlob.EndsWith('\*')) { $directoryGlob } elseif ($directoryGlob.EndsWith('\')) { "^""$($directoryGlob)*"^"" } else { "^""$($directoryGlob)\*"^"" } )"^""; $expandedPath = [System.Environment]::ExpandEnvironmentVariables($pathGlobPattern); Write-Host "^""Searching for items matching pattern: `"^""$($expandedPath)`"^""."^""; $deletedCount = 0; $failedCount = 0; $foundAbsolutePaths = @(); Write-Host 'Iterating files and directories recursively.'; try {; $foundAbsolutePaths += @(; Get-ChildItem -Path $expandedPath -Force -Recurse -ErrorAction Stop | Select-Object -ExpandProperty FullName; ); } catch [System.Management.Automation.ItemNotFoundException] {; <# Swallow, do not run `Test-Path` before, it's unreliable for globs requiring extra permissions #>; }; try {; $foundAbsolutePaths += @(; Get-Item -Path $expandedPath -ErrorAction Stop | Select-Object -ExpandProperty FullName; ); } catch [System.Management.Automation.ItemNotFoundException] {; <# Swallow, do not run `Test-Path` before, it's unreliable for globs requiring extra permissions #>; }; $foundAbsolutePaths = $foundAbsolutePaths | Select-Object -Unique | Sort-Object -Property { $_.Length } -Descending; if (!$foundAbsolutePaths) {; Write-Host 'Skipping, no items available.'; exit 0; }; Write-Host "^""Initiating processing of $($foundAbsolutePaths.Count) items from `"^""$expandedPath`"^""."^""; foreach ($path in $foundAbsolutePaths) {; if (-not (Test-Path $path)) { <# Re-check existence as prior deletions might remove subsequent items (e.g., subdirectories). #>; Write-Host "^""Successfully deleted: $($path) (already deleted)."^""; $deletedCount++; continue; }; try {; Remove-Item -Path $path -Force -Recurse -ErrorAction Stop; $deletedCount++; Write-Host "^""Successfully deleted: $($path)"^""; } catch {; $failedCount++; Write-Warning "^""Unable to delete $($path): $_"^""; }; }; Write-Host "^""Successfully deleted $($deletedCount) items."^""; if ($failedCount -gt 0) {; Write-Warning "^""Failed to delete $($failedCount) items."^""; }"
```

I think we should keep the issue with another name, but I'm not sure if it's good to do this or not due to mentioned concern.

**Comment by DaborTech1** [comment]
@echo off

title Run as Administrator

fltmc >nul 2>&1 || (PowerShell Start -Verb RunAs '%~S0' & exit)

echo Running as Administrator directory
 
pause
