### ISSUE TITLE
your website is down https://privacy.sexy

### ISSUE THREAD

**Issue by NolonQ** [undergroundwires/privacy.sexy#288]
### Description
This isn't a bugreport, just wanted to inform you that your website cannot be reached.
Isn't a real issue as we can still download github releases.
Your script is SERIOUSLY underrated, many thanks for this!!
There are many tools advertised for windows but not on the level of this.
I don't get why this superior project get's less attention than most weaker and more popular options.

**Comment by undergroundwires** [comment]
Hi @NolonQ, thank you for the nice comments. It's really nice to hear such things occasionally as GitHub issues usually full of complaints 😛

https://privacy.sexy works fine for me on different devices.

Is it possible that you're on corporate network where they blocked `*.sexy` TLD completely? What devices did you test it on? And what browser?

**Comment by NolonQ** [comment]
> Hi @NolonQ, thank you for the nice comments. It's really nice to hear such things occasionally as GitHub issues usually full of complaints 😛
> 
> https://privacy.sexy works fine for me on different devices.
> 
> Is it possible that you're on corporate network where they blocked `*.sexy` TLD completely? What devices did you test it on? And what browser?

Apologies for the late reply, i mean it you helped me ALOT with all the code you offer for free, can't thank you enough for that!
This project really deserves more attention. Instead of 3000 stars on github this should have 30000.
uBlockOrigin now has 41000 stars, it's great ofc but it's adblocker for a webbrowser while privacysexy modifieds the whole operatingsystem, in my opinion this has greater value, your script improved my systemperformance and privacy!

About the issue, i believe the problem must have been me. Probably was a network related issue but i can reach your site again now.
I hope one day a large youtuber will cover privacysexy to bring the attention to the project that it deserves.
The portmaster firewall from safing.io recently was mentioned in a video from thepcsecurity channel and after that the project gained around +1500 stars on github and many new downloads.
From all the performance and privacy tools i tried for windows this is my favorite by far.
I also had some issues using your script, some things went broken but i didn't complain because you did warn about this and so i spent alot of time testing all the options in a vm and i'm very happy with the result, thanks again for you work, appreciate it very much!
