### ISSUE TITLE
[BUG]: Misslabeled Remove MSPaint

### ISSUE THREAD

**Issue by Texbio** [undergroundwires/privacy.sexy#292]
Under 'REMOVE BLOATWARE', one of the 'Remove "Paint 3D" app' removes MSPaint and is labeled incorrectly, it should be  'Remove "Paint" app' or a better alternative.
![image](https://github.com/undergroundwires/privacy.sexy/assets/36513888/626051a7-ffd8-4862-9ff3-b81952f2cb24)

**Comment by undergroundwires** [comment]
Hi @Texbio, thanks for the bug report.

The Microsoft store app URL for this app is [`https://apps.microsoft.com/detail/9NBLGGH5FV99?hl=en-us&gl=US`](https://apps.microsoft.com/detail/9NBLGGH5FV99?hl=en-us&gl=US). Let's verify that the store app name is **Paint 3D**.

Following [Microsoft docs](https://learn.microsoft.com/en-us/mem/configmgr/protect/deploy-use/find-a-pfn-for-per-app-vpn) we can get package information by using this pattern: `https://bspmts.mp.microsoft.com/v1/public/catalog/Retail/Products/<app id>/applockerdata`. We get the app ID from previous store URL, which is `9NBLGGH5FV99`. So the URL becomes: https://bspmts.mp.microsoft.com/v1/public/catalog/Retail/Products/9NBLGGH5FV99/applockerdata. Visiting this URL gives this package information:

```json
{
  "packageFamilyName": "Microsoft.MSPaint_8wekyb3d8bbwe",
  "packageIdentityName": "Microsoft.MSPaint",
  "windowsPhoneLegacyId": "24d84647-7b95-4855-bb18-55d608c880a1",
  "publisherCertificateName": "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"
}
```

We can verify that privacy.sexy is removing exactly this package, with name name of `Microsoft.MSPaint` and publisher ID `8wekyb3d8bbwe`. 

I know this is confusing but Microsoft named this package `Microsoft.MSPaint` but branded it to "Paint 3D". So the UI/label is right.
