### ISSUE TITLE
Am I free to use codes in my projects?

### ISSUE THREAD

**Issue by bakmosta3** [undergroundwires/privacy.sexy#297]
Am I free to use the codes in any way in my projects?

**Comment by Paladynee** [comment]
RDFL

**Comment by undergroundwires** [comment]
Hi @bakmosta3.

Currently, the privacy.sexy source code and the scripts generated by it are licensed under the GNU Affero General Public License v3.0 (AGPL 3.0). This is a [free-software license](https://en.wikipedia.org/wiki/Free-software_license), which means you are free to use, modify, and share the codes under certain conditions. As @Paladynee pointed out, the licensing details are in the [LICENSE](https://github.com/undergroundwires/privacy.sexy/blob/master/LICENSE) file. 

If the AGPL 3.0 license doesn't suit your needs (for instance, if you're working on a commercial, closed-source project), feel free to [contact me directly](https://undergroundwires.dev/me/). We can discuss the possibility of re-licensing or granting specific rights for your use case.

While attribution is not required, it is appreciated if you could mention privacy.sexy in your project. Additionally, you're welcome to share your project in the discussion section of our repository. I actively try to support projects that derive from or depend on privacy.sexy.

**Comment by undergroundwires** [comment]
Hi @bakmosta3.

Currently, the privacy.sexy source code and the scripts generated by it are licensed under the GNU Affero General Public License v3.0 (AGPL 3.0). This is a [free-software license](https://en.wikipedia.org/wiki/Free-software_license), which means you are free to use, modify, and share the codes under certain conditions. As @Paladynee pointed out, the licensing details are in the [LICENSE](https://github.com/undergroundwires/privacy.sexy/blob/master/LICENSE) file. 

If the AGPL 3.0 license doesn't suit your needs (for instance, if you're working on a commercial, closed-source project), feel free to [contact me directly](https://undergroundwires.dev/me/). We can discuss the possibility of re-licensing or granting specific rights for your use case.

It is appreciated if you could mention privacy.sexy somewhere visible in your project, but not required. Additionally, you're welcome to share your project in the discussions section. I actively try to support projects that derive from or depend on privacy.sexy.
