### ISSUE TITLE
Add Dark Mode to privacy.sexy website

### ISSUE THREAD

**Issue by BOY0038v2** [undergroundwires/privacy.sexy#301]
### Problem description

I would like dark mode on the website, it would be very nice for my eyes...

### Proposed solution

A light/dark mode button would be great
I know there are more important things to work on, but i think it would be a great improvement
Thanks in advance

**Comment by undergroundwires** [comment]
Hi @BOY0038v2 , thanks for the empathy. As you mention, it's a lot of things going around the project, so I do not find the time to add features for now I want but focus heavily on stabilizing it.

I'm open to contributions for it. The theming should be straightforward, if someone with good eyes can provide nice colors I can add the switch / OS default check to provide the theme.

You can read more at #205, and let's continue the discussion there to avoid duplicates.
