### ISSUE TITLE
AirDrop macOS Sonoma 14.2.1

### ISSUE THREAD

**Issue by AlexanderDankin** [undergroundwires/privacy.sexy#306]
I can't get the function to enable AirDrop to work back. Devices do not find the Mac.

**Comment by undergroundwires** [comment]
Hi @AlexanderDankin, what script did you execute?

**Comment by AlexanderDankin** [comment]
"Disable AirDrop file sharing"

**Comment by undergroundwires** [comment]
Revert that one, if it's not working it's something else, and I cannot troubleshoot without having script file. Feel free to let me know if you figure out reverting what solves it so we can fix it. Closing this until a better reproduction case is provided as suggested in issue template.
