### ISSUE TITLE
[BUG]: windows defender flags standard with having wacatac trojan

### ISSUE THREAD

**Issue by Pe6r0** [undergroundwires/privacy.sexy#325]
I'm using Win11 Pro. Why is it flagging it, which option is making it?

**Comment by femdiya** [comment]
False positive

**Comment by undergroundwires** [comment]
Please report this as false-positive on whatever AV you're using.
privacy.sexy is committed to your security, see [SECURITY.md](https://github.com/undergroundwires/privacy.sexy/blob/0.13.0/SECURITY.md#security-practices).
