### ISSUE TITLE
Revert Changes

### ISSUE THREAD

**Issue by please55** [undergroundwires/privacy.sexy#33]
Looks really promising.

Trying this out for the first time and its not clear to me how to revert changes made. 

Lets say I make a custom set of changes. 3 months later, I need to revert a few.  How does one painlessly recreate the same selection set so to not miss any previous changes and revert as needed?

Could there be an upload or perhaps a code that could be entered that would bring up a previous selection to continue making or undoing changes to?

**Comment by undergroundwires** [comment]
Hi @please55 👋, thanks for the feature request and trying out the software. Sorry for coming back late, I had a little vacation before the winter 😎.

I agree that we need this feature.

As you already realized, we do not have no automatic (painless) way to restore to any user state. I was considering adding some kind of "save" option and I really love your suggested solution: parsing the generated file.

The solution will have challenges as privacy.sexy has been iterating pretty quickly. States that may change after a script generation include:

- Changing underlying code of the script
- Renaming the script while the code stays the same.
- Adding new scripts to a category that was selected by the user.
- Removing scripts that were selected by the user (if a script is both renamed with changes to its code it would then be interpreted as "removal" as well)

I wonder what would be a good way to handle those changes 🤔. Showing some kind of report after uploading a script is probably a boring user experience but sounds like a good starting point.

After this gets implemented, it also enables functionalities as remembering latest user settings in both browser/desktop versions.

Another functionality required to achieve what you want is one more button called something like "revert all selected" that will automatically toggle revert state for all of the scripts.

**Comment by undergroundwires** [comment]
Hi @please55 👋, thanks for the feature request and trying out the software. Sorry for coming back late, I had a little vacation before the winter 😎.

I agree that we need this feature.

As you already realized, we do not have no automatic (painless) way to restore to any user state. I was considering adding some kind of "save" option and I really love your suggested solution: parsing the generated file.

The solution will have challenges as privacy.sexy has been iterating pretty quickly. States that may change after a script generation include:

- Changing underlying code of the script
- Renaming the script while the code stays the same.
- Adding new scripts to a category that was selected by the user.
- Removing scripts that were selected by the user (if a script is both renamed with changes to its code it would then be interpreted as "removal" as well)

I wonder what would be a good way to handle those changes 🤔. Showing some kind of report after uploading a script is probably a boring user experience but sounds like a good starting point.

After this gets implemented, it also enables functionalities as remembering latest user settings in both browser/desktop versions.

Another functionality required is one more button called something like "revert all selected" that will automatically toggle revert state for all of the scripts for the current user selection.

**Comment by undergroundwires** [comment]
Hi @please55 👋, thanks for the feature request and trying out the software. Sorry for coming back late, I had a little vacation before the winter 😎.

I agree that we need this feature.

As you already realized, we do not have no automatic (painless) way to restore to any user state. I was considering adding some kind of "save" option and I really love your suggested solution: parsing the generated file.

The solution will have challenges as privacy.sexy has been iterating pretty quickly. States that may change after a script generation include:

- Changing underlying code of the script
- Renaming the script while the code stays the same.
- Adding new scripts to a category that was selected by the user.
- Removing scripts that were selected by the user (if a script is both renamed with changes to its code it would then be interpreted as "removal" as well)

I wonder what would be a good way to handle those changes 🤔. Showing some kind of report after uploading a script is probably a boring user experience but sounds like a good starting point.

After this gets implemented, it also enables being able to remember latest user selection.

Another functionality required is one more button called something like "revert all selected" that will automatically toggle revert state for all of the scripts for the current user selection.

**Comment by undergroundwires** [comment]
Hi @please55 👋, thanks for the feature request and trying out the software. Sorry for coming back late, I had a little vacation before the winter 😎.

I agree that we need this feature.

As you already realized, we do not have no automatic (painless) way to restore to any user state. I was considering adding some kind of "save" option and I really love your suggested solution: parsing the generated file.

The solution will have challenges as privacy.sexy has been iterating pretty quickly. States that may change after a script generation include:

- Changing underlying code of the script
- Renaming the script while the code stays the same.
- Adding new scripts to a category that was selected by the user.
- Removing scripts that were selected by the user (if a script is both renamed with changes to its code it would then be interpreted as "removal" as well)

I wonder what would be a good way to handle those changes 🤔. Showing some kind of report after uploading a script is probably a boring user experience but sounds like a good starting point.

After this gets implemented, it also enables being able to remember latest user selection as we could write the current user script to local storage as it gets updated.

Another functionality required is one more button called something like "revert all selected" that will automatically toggle revert state for all of the scripts for the current user selection.

**Comment by undergroundwires** [comment]
Closing this issue as this will eventually get implemented by #59
