### ISSUE TITLE
[BUG]: Copilot keeps turning back on after restarting PC

### ISSUE THREAD

**Issue by hhoneeyy** [undergroundwires/privacy.sexy#335]
### Description

Copilot keeps turning back on after restarting PC

### OS

--> Windows 11

### Reproduction steps

1) Run the privacy script
2) it works
3) Restart pc
4) keybind "Win + C" still makes copilot pop up

[privacy-script.txt](https://github.com/undergroundwires/privacy.sexy/files/14735231/privacy-script.txt)

**Comment by undergroundwires** [comment]
High, which edition of Windows are you running? Home? And which version?

**Comment by hhoneeyy** [comment]
> High, which edition of Windows are you running? Home? And which version?

Wndows 11 home 23H2

**Comment by undergroundwires** [comment]
It may not be possible to "disable it proper way" in Home version as `TurnOffWindowsCopilot` group policy will not be supported. It should work on pro editions.

There can be more "hacky" way to disable it. I'm open to suggestions.

**Comment by hhoneeyy** [comment]
> It may not be possible to "disable it proper way" in Home version as `TurnOffWindowsCopilot` group policy will not be supported. It should work on pro editions.
> 
> There can be more "hacky" way to disable it. I'm open to suggestions.

Hello again, i changed my PC from home to pro, but copilot is still enabled after restart, what do i do?

**Comment by undergroundwires** [comment]
Thank you for information. This should not be happening. Can anyone else here reproduce this?

**Comment by undergroundwires** [comment]
Thank you for information. This should not be happening.

I guess you run the script on W11 pro. Could you share a screenshot of copilot you see?

**Comment by undergroundwires** [comment]
This would resolve the issue:

```batchfile
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v "DisabledHotkeys" /t "REG_SZ" /d "C" /f
```

After this restart your explorer:

```batchfile
taskkill /f /im explorer.exe & start explorer
```

I will add this to next patch.

**Comment by undergroundwires** [comment]
This will resolve the issue with editions without GPO support:

```batchfile
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v "DisabledHotkeys" /t "REG_SZ" /d "C" /f
```

After this restart your explorer:

```batchfile
taskkill /f /im explorer.exe & start explorer
```

I will add this to next patch.
