### ISSUE TITLE
[Bug]: "Disable text and handwriting data collection" missing

### ISSUE THREAD

**Issue by TobyGiacometti** [undergroundwires/privacy.sexy#369]
`Disable OS Data Collection/Disable text and handwriting data collection` is missing in the web app since version 0.13.4. Looks like it is caused by a syntax error:

https://github.com/undergroundwires/privacy.sexy/blob/8341411be434c6d145e942b1792020ccf02f58c8/src/application/collections/windows.yaml#L4315

The mapping for the `Disable location access` category is missing a dash.

**Comment by undergroundwires** [comment]
Thanks for the great bug report @TobyGiacometti. It gives all the necessary information and you identify the source of the bug. In addition to fixing the bug on place you show, I will:

- Stricter YAML linting.
- Add automated schema validation in compiler, either homemade or [standard YAML schema](https://yaml.org/spec/1.2.2/#recommended-schemas).

This would prevent similar issues in future through automated tests.

**Comment by undergroundwires** [comment]
Thanks for the great bug report @TobyGiacometti. It gives all the necessary information and you identify the source of the bug. In addition to fixing the bug on place you show, I will:

1. Add stricter YAML linting, current YAML linter is not effective.
2. Add additional in compiler for unnecessary properties.
3. Add automated YAML schema validation as [standard YAML schema](https://yaml.org/spec/1.2.2/#recommended-schemas) support its.

This would prevent similar issues in future through automated tests and provide the necessary quality gates.

**Comment by undergroundwires** [comment]
Adding stricter validation in compiler/parser and YAML schema, I see that:

- Some Windows scripts are not being recommended due to incorrect usage of `recommended: standard` instead of `recommend: standard`.
- On macOS, a category having recommendation (`recommend` property), which is not supported.
- Some scripts are missing logic due to wrong function calls in Windows
- Unsupported non-string parameter values are being used relying side-effects of the compiler.

All of this will be fixed and included in next patch.

**Comment by undergroundwires** [comment]
This has driven a lot of improvements and bunch of other issues. Special thanks again @TobyGiacometti, great contribution, hope to see you around more.

Released as part of [0.13.5](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.5) 🚀.

**Comment by TobyGiacometti** [comment]
Thank you! You could have just fixed the bug I reported, instead you improved the architecture to prevent such bugs from showing up in the future. Great work!
