### ISSUE TITLE
[Bug]: Wi-Fi not working on startup, or after waking up PC from sleep

### ISSUE THREAD

**Issue by kexo1** [undergroundwires/privacy.sexy#371]
### Description

Everytime I turn on PC, the Wi-Fi is not responding (I get DNS errors in browser), to fix it I have to manually turn off Wi-Fi and then turn in back on - then it works normally.
This started happening after running the script. It's not a huge bug, however it's annyoing that i have to re-enable Wi-Fi so often.

OS:
Microsoft Windows 11 Home
Version 10.0.22621 Build 22621

Script:
https://drive.google.com/file/d/1SbHD0BfxU4W2WT2pCVnMiMEDRjTaZjEr/view?usp=sharing
password: privacy

### Reproduction steps

Run the script
Restart PC
The Wi-Fi is showing it's connected, however everything that requires internet doesn't work

### Expected behavior

Well I expect to have Wi-Fi working on startup

**Comment by kexo1** [comment]
![image](https://github.com/undergroundwires/privacy.sexy/assets/115703948/f0867a57-e7a3-431f-b72f-11e5ec796830)
I forgot to mention that i use NextDNS on my PC, but that DNS never showed these kinds of problems
As I am testing it right now, some sites might load but partially (maybe web-cache?), some elements are missing/not working

**Comment by undergroundwires** [comment]
I'm not able to test this. For those who can, attaching the script file you shared: [privacy-script.txt](https://github.com/user-attachments/files/15749170/privacy-script.txt) as future reference.

**Comment by plantindesk** [comment]
@kexo1 Did you run the command `ipconfig /flushdns` cause this will clear your local DNS cache, ensuring that your system starts using NextDNS resolution properly.

**Comment by kexo1** [comment]
I ran flushdns command and reverted NetBios protocol but it didn't fix my problem

**Comment by plantindesk** [comment]
@kexo1 "Try reverting all the selected scripts so we can confirm if there are any issues with them."

**Comment by kexo1** [comment]
I will be reverting them one by one and test it, please do note close issue, I will respond whcih one was the problem after I am done

**Comment by kexo1** [comment]
Reverting option "Improve network security" + removing NextDNS app and replacing it with traditional DNS settings trough windows fixed the issue

**Comment by undergroundwires** [comment]
Hi @kexo1, it would be very valuable if you can figure out exactly what script has caused this, if you can reproduce this. You can enabling each script under "Improve network security" until you found out the problematic one. This would help us to document it, discourage/remove/modify script as needed to help others and make privacy.sexy better for all of us in future :)
