### ISSUE TITLE
[Bug]: Can't set a desktop wallapaper or lockscreen background

### ISSUE THREAD

**Issue by Turtlecute33** [undergroundwires/privacy.sexy#388]
### Description

I can't set a desktop wallpaper or open the "wallpaper" or "lockscreen background" section in "personalize" settings.

### How can the bug be recreated?

i runned the script on a clean windows 11 pro machine

### Operating system

Windows 11 pro

### Script file

https://gist.github.com/Turtlecute33/b7a751fb3935d9423b4dcff1f77075a5

**Comment by undergroundwires** [comment]
1. Can you share a screenshot @Turtlecute33? What happens when you try to open it?
2. What version of Windows 11 Pro are you using? Is it 23H2? ("Start button" > "Settings" > "System" > "About").

**Comment by Turtlecute33** [comment]
> 1. Can you share a screenshot @Turtlecute33? What happens when you try to open it?

I can't take a screenshot of it because basically nothing happens. When I click on "background" section, the settings app freezes for about 10 seconds, and I can't click anything. After a while, Windows opens the background page, but if I change the image, the wallpaper becomes black. If I try to set a custom image as the background, it doesn't apply it as the wallpaper but instead sets the background to a solid black color.

If i try to set as background a presentation windows sets as background the default ones in the theme.


> 2. What version of Windows 11 Pro are you using? Is it 23H2? ("Start button" > "Settings" > "System" > "About").

Windows 11 Pro 23H2

**Comment by undergroundwires** [comment]
Tested the script on Windows 11 23H2. It works fine for me. Background page loads fast and image can be changed to custom or existing ones.

![image](https://github.com/user-attachments/assets/97f481eb-2d9e-4f8a-913f-2581cffab94d)

**Comment by Turtlecute33** [comment]
https://github.com/user-attachments/assets/3b4e7398-f87c-4f1f-b2f8-2154aac83f4a

that's what happen on my screen (i used several privacy.sexy script in the past and i don't know which one broke wallpapers but i never used other debloating tools)

**Comment by plantindesk** [comment]
![image](https://github.com/user-attachments/assets/2ab77e07-af32-4fc2-8de9-f4ca4cceef8e)

Try this

**Comment by Turtlecute33** [comment]
@plantindesk this what?

If i try right click and set as background i ve the same problem

**Comment by Turtlecute33** [comment]
There was a corrupted files in the windoes theme folder. The issue was not privacy,sexy related. 

Thanks a lot for the help!
