### ISSUE TITLE
[Bug]: Defender detection. (Most likely false-positive)

### ISSUE THREAD

**Issue by femdiya** [undergroundwires/privacy.sexy#392]
### Description

Enabled all scripts at the same time, downloaded the .bat file from the site, defender blocked it (false positive)

### Reproduction steps

1. Enable all scripts on the website (for debugging proposes)
2. Download the file
3. File gets blocked by defender, have to add a exception for this file.

### Expected behavior

Defender should not block this script (?)

### Screenshots

![image](https://github.com/user-attachments/assets/61bd9089-ee5a-4cc5-b707-c1d6b9f0e780)

### privacy.sexy environment details

Windows 11 Home Version 23H2 Build 22631.3880
Firefox 128.0.3
Security intelligence version 1.415.396.0

### Additional context

[VirusTotal Scan link](https://www.virustotal.com/gui/file/82a69c524ec0fde09b3dafb930f36bf1d10beb309aa844097ec457731c083d30?nocache=1)
[Microsoft reference link 1](https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:PowerShell/MpTamperPShell.HD&threatid=2147898122)
[Microsoft reference link 2](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3APowerShell%2FMpTamperPShell.HD&threatid=2147898122)
[privacy-script.zip](https://github.com/user-attachments/files/16440846/privacy-script.zip)

**Comment by femdiya** [comment]
I personally think that there should be a warning on the website/app of the project which points out to possible false-positives.

**Comment by femdiya** [comment]
@plantindesk You're correct, but see the comment below https://github.com/undergroundwires/privacy.sexy/issues/392#issuecomment-2260348996

**Comment by plantindesk** [comment]
@femdiya That's a nice idea. Additionally, I was considering a complete redesign of the project's user interface. However, I don't think this will be accepted, as I believe they think there is no need for it.

**Comment by femdiya** [comment]
Nevermind actually,
In the website, it is addressed that Windows Defender will block the downloaded script.

**Comment by femdiya** [comment]
> Nevermind actually, In the website, it is addressed that Windows Defender will block the downloaded script.

![image](https://github.com/user-attachments/assets/db338c0f-dc9e-4b8c-acd3-6febf0ec3def)
