### ISSUE TITLE
Add macOS support

### ISSUE THREAD

**Issue by undergroundwires** [undergroundwires/privacy.sexy#40]
- [x] Do necessary refactorings to allow more than one OS
- [x] Add initial scripts / tweaks

**Comment by necros2k7** [comment]
Android and *nix scripts could be also cool

**Comment by undergroundwires** [comment]
Now this is live 🎉

I agree @necros2k7 . I lack knowledge about those though. Will add Ubuntu somewhere in future though. I would accept PRs for any other OS. It would be as easy as adding a new yaml file in [collections](https://github.com/undergroundwires/privacy.sexy/tree/master/src/application/collections).
