### ISSUE TITLE
[Bug]: ServiceKeepAlive must be set to 0 to properly disable Windows Defender.

### ISSUE THREAD

**Issue by Od1sseas** [undergroundwires/privacy.sexy#426]
### Description

I noticed that in the script ServiceKeepAlive is set to 1. This is wrong. The value must be set to 0 to properly disable Windows Defender.

https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsDefender::ServiceKeepAlive

### How can the bug be recreated?

:: ----------------------------------------------------------
:: --------Disable always running antimalware service--------
:: ----------------------------------------------------------
echo --- Disable always running antimalware service
PowerShell -ExecutionPolicy Unrestricted -Command "$data = '1'; reg add 'HKLM\Software\Policies\Microsoft\Windows Defender' /v 'ServiceKeepAlive' /t 'REG_DWORD' /d "^""$data"^"" /f"
:: ----------------------------------------------------------

**Comment by undergroundwires** [comment]
Fix released as part of [0.13.7](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.7) 🚀. It fixes the value with extensive documentation as part of 0900492ccba8788471886a5b473a7c744dbfb991. Feel free to test it and open new issue if there are any other issues. Thank you again.
