### ISSUE TITLE
Cortana removal on latest builds of Windows

### ISSUE THREAD

**Issue by sopla4ever** [undergroundwires/privacy.sexy#43]
Cortana removal doesn't work on new builds (i.e. 20241.1005).
I can uninstall it by IObit Uninstaller succesfull.

**Comment by undergroundwires** [comment]
Thanks for the bug report and testing this 🙌

`PowerShell -Command "Get-AppxPackage "Microsoft.549981C3F5F10" | Remove-AppxPackage"` should work on Windows 2004.

I'll add that under "Remove bloatware" > "Uninstall Windows store apps" > "System apps" > "Cortana" > "Cortana app".

It's unfortunately not documented in the [official documentation](https://docs.microsoft.com/en-us/windows/application-management/apps-in-windows-10#system-apps) and therefore missing.

**Comment by sopla4ever** [comment]
Recently, I haven't had time to look at the code.  The current system base for insider is 2103 aka 21H1.  I will try to reinstall the system in the coming days.  I'll check if this command works there.  I can make an appx list in compilation from branch 2103.

Branch 2009 (20H2) is currently latest public version.  If someone has this branch, please test this.

**Comment by undergroundwires** [comment]
It should work now with the latest version. Feel free to create a new issue or reopen this one if it does not work.
