### ISSUE TITLE
[Bug]: eu.battle.net by blizzard entertainment does not let me log in anymore

### ISSUE THREAD

**Issue by CodingMadness** [undergroundwires/privacy.sexy#430]
### Description

Hey, 

as stated in the tilte, after running a custom, but kinda deep, selection of what I want to be removed by the tool, I (must have consequently) disabled something which is needed by "eu.battle.net" launcher to be able to log me in, interesstingly enough, I can play other Steam games, can log into steam, into league of legends and can browse through "Wallpaper Engine" and generally through the internet without issues, but I am not able to log into blizzards launcher anymore, I would be so glad if you guys could help me out, I was dumb enough to not make a restore point before those changes...... so thats on me, but I would be giga glad if you guys can tell me what I have messed up that bad for it not to log me in anymore... 

I get only the issue "BLZBNTBGS80000011" from the launcher when trying to log in with my correct credentials... 

Any info on this would be super good, here the script I used to do that

Also my internet connectivcity symbol is gone, it permanently telly me i have no internet connection even tho thats false, because I do have internet.

PS: I did click the "strict" strict version, so if you want to maybe look up what that could cause it, you can easily look up that on your app version :)

### Reproduction steps

1. Open "Privacy is sexy" desktop app with admin rights
2. Select "strict" in the selection tab
3. disable COMPLETELY windows defender and shut down firewall
4. Run the script
5. Restart PC
6. Log into battle.net launcher and check if it logs you in

### Expected behavior

I expected to log into my b-net account but nope.

### Screenshots

Sadly the script somehow blocks clipboard services and when i try to reactivate it doesnt let me in the "Services" program.... 

I would have shown otherwise the detailed picture...

### privacy.sexy environment details

Desktop version; Windows 11 23H2 x64

### Additional context

none.

**Comment by plantindesk** [comment]
- Can you provide the logs of Blizzard Entertainment
- Have you tried reverting the hosts that were disabled by the script?

**Comment by CodingMadness** [comment]
> Hi @CodingMadness,
> 
>     * Could you please provide the logs for Blizzard Entertainment?
> 
>     * Also, have you tried reverting the hosts that were disabled by the script?

1. What logs do you mean specifically
2. i did that but sadly, nothing changed...

**Comment by CodingMadness** [comment]
> TLS

ngl, I did not know that it was that specifc ancient tech they use but I for sure knew they still make use of something very very old, but did not know thaaaat old (tls 1.0 - 1999) nice, what  scum company, sadly i like some of their damn games.... 

but thx alot bro!!

**Comment by undergroundwires** [comment]
See: https://github.com/undergroundwires/privacy.sexy/issues/181#issuecomment-2211749777

I'm not sure what to do for privacy.sexy, these TLS versions should really not be used at all.

**Comment by CodingMadness** [comment]
> See: [#181 (comment)](https://github.com/undergroundwires/privacy.sexy/issues/181#issuecomment-2211749777)
> 
> I'm not sure what to do for privacy.sexy, these TLS versions should really not be used at all.

Please read the chat I have had with DeepSeek AI (dont shy away because i use it xd)

> is there a possibility to basically only have TLS 1.0 and SHA-1 be enabled ONLY when blizzard games are running and then faulting back to the secure newer versions for both respectively?

Yes! This is actually a brilliant approach - we can use application-specific TLS policies and scheduled tasks to toggle these settings only when [Battle.net](https://battle.net/) runs. Here's how:
Method 1: App-Specific TLS via Environment Variables (Cleanest)

Create a batch file that sets TLS environment variables only for [Battle.net](https://battle.net/) process tree:
batch

@echo off
REM ============================================
REM Battle.net Legacy TLS Enabler
REM Save as: BattleNet_LegacyTLS.bat
REM Run as Administrator
REM ============================================

setlocal

echo Configuring legacy TLS for Battle.net only...

REM 1. Force .NET Framework (used by Battle.net) to use legacy TLS
REM This only affects processes launched from this batch file
set COMPAT_TLS=1.0,1.1,1.2
set SSL_CERT_FILE=%ProgramFiles(x86)%\Battle.net\Certificates\blizzard.pem

REM 2. Set registry keys temporarily (affects all apps but we'll revert)
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client" /v Enabled /t REG_DWORD /d 1 /f
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client" /v DisabledByDefault /t REG_DWORD /d 0 /f

reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client" /v Enabled /t REG_DWORD /d 1 /f
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client" /v DisabledByDefault /t REG_DWORD /d 0 /f

REM 3. Enable SHA-1 temporarily
reg add "HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319" /v SchUseStrongCrypto /t REG_DWORD /d 0 /f
certutil -setreg chain\ChainMinSHA1PubKeyBitLength 0

REM 4. Restart cryptographic services to apply changes
net stop CryptSvc /y
timeout /t 2
net start CryptSvc

REM 5. Launch Battle.net
echo Starting Battle.net with legacy TLS enabled...
start "" /D "%ProgramFiles(x86)%\Battle.net" "Battle.net Launcher.exe"

REM 6. Wait for Battle.net to start
timeout /t 10

:MONITOR
REM Check if Battle.net or any Blizzard game is still running
tasklist /FI "IMAGENAME eq Battle.net.exe" /FI "STATUS eq RUNNING" | find /I "Battle.net.exe" > nul
if %errorlevel%==0 goto WAIT

tasklist /FI "IMAGENAME eq Battle.net Launcher.exe" /FI "STATUS eq RUNNING" | find /I "Battle.net Launcher.exe" > nul
if %errorlevel%==0 goto WAIT

REM Check for common Blizzard games
tasklist /FI "IMAGENAME eq Overwatch.exe" | find /I "Overwatch.exe" > nul
if %errorlevel%==0 goto WAIT

tasklist /FI "IMAGENAME eq Wow.exe" | find /I "Wow.exe" > nul
if %errorlevel%==0 goto WAIT

tasklist /FI "IMAGENAME eq Diablo IV.exe" | find /I "Diablo IV.exe" > nul
if %errorlevel%==0 goto WAIT

tasklist /FI "IMAGENAME eq ModernWarfare.exe" | find /I "ModernWarfare.exe" > nul
if %errorlevel%==0 goto WAIT

REM No Blizzard processes found, revert settings
echo No Battle.net processes found. Reverting to secure TLS...
goto REVERT

:WAIT
timeout /t 30
goto MONITOR

:REVERT
echo Reverting TLS settings to secure defaults...

REM Disable TLS 1.0/1.1
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client" /v Enabled /t REG_DWORD /d 0 /f
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client" /v DisabledByDefault /t REG_DWORD /d 1 /f

reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client" /v Enabled /t REG_DWORD /d 0 /f
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client" /v DisabledByDefault /t REG_DWORD /d 1 /f

REM Re-enable strong crypto
reg add "HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319" /v SchUseStrongCrypto /t REG_DWORD /d 1 /f
certutil -setreg chain\ChainMinSHA1PubKeyBitLength 1024

REM Restart cryptographic services
net stop CryptSvc /y
timeout /t 2
net start CryptSvc

echo Secure TLS settings restored!
pause

Method 2: PowerShell Script with Process Monitoring

This is more robust and handles edge cases better:
powershell

# Save as: BattleNet-TLS-Toggle.ps1
# Run as Administrator

# Function to enable legacy TLS
function Enable-LegacyTLS {
    Write-Host "Enabling legacy TLS for Blizzard..." -ForegroundColor Yellow
    
    # Enable TLS 1.0 and 1.1
    $tlsPaths = @(
        "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client",
        "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client"
    )
    
    foreach ($path in $tlsPaths) {
        if (-not (Test-Path $path)) {
            New-Item -Path $path -Force | Out-Null
        }
        Set-ItemProperty -Path $path -Name "Enabled" -Value 1 -Type DWord
        Set-ItemProperty -Path $path -Name "DisabledByDefault" -Value 0 -Type DWord
    }
    
    # Allow SHA-1
    certutil -setreg chain\ChainMinSHA1PubKeyBitLength 0
    
    # Restart crypto service
    Restart-Service -Name CryptSvc -Force
    Start-Sleep -Seconds 2
    
    Write-Host "Legacy TLS enabled." -ForegroundColor Green
}

# Function to disable legacy TLS
function Disable-LegacyTLS {
    Write-Host "Disabling legacy TLS (re-enabling security)..." -ForegroundColor Yellow
    
    $tlsPaths = @(
        "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client",
        "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client"
    )
    
    foreach ($path in $lsPaths) {
        if (Test-Path $path) {
            Set-ItemProperty -Path $path -Name "Enabled" -Value 0 -Type DWord
            Set-ItemProperty -Path $path -Name "DisabledByDefault" -Value 1 -Type DWord
        }
    }
    
    # Block SHA-1
    certutil -setreg chain\ChainMinSHA1PubKeyBitLength 1024
    
    # Restart crypto service
    Restart-Service -Name CryptSvc -Force
    
    Write-Host "Secure TLS settings restored." -ForegroundColor Green
}

# Function to monitor Blizzard processes
function Monitor-BlizzardProcesses {
    $blizzardProcesses = @(
        "Battle.net",
        "Battle.net Launcher",
        "Overwatch",
        "Wow",
        "WowClassic", 
        "Diablo IV",
        "Diablo III",
        "Hearthstone",
        "Heroes of the Storm",
        "StarCraft II",
        "ModernWarfare",
        "Call of Duty HQ",
        "Destiny2"
    )
    
    Write-Host "Monitoring Blizzard processes..." -ForegroundColor Cyan
    Write-Host "Press Ctrl+C to exit and revert TLS settings" -ForegroundColor Gray
    
    # Enable legacy TLS at start
    Enable-LegacyTLS
    
    try {
        while ($true) {
            $anyRunning = $false
            
            foreach ($proc in $blizzardProcesses) {
                if (Get-Process -Name $proc -ErrorAction SilentlyContinue) {
                    $anyRunning = $true
                    break
                }
            }
            
            if (-not $anyRunning) {
                Write-Host "No Blizzard processes found. Waiting 30 seconds before reverting..." -ForegroundColor Yellow
                Start-Sleep -Seconds 30
                
                # Double-check
                $anyRunning = $false
                foreach ($proc in $blizzardProcesses) {
                    if (Get-Process -Name $proc -ErrorAction SilentlyContinue) {
                        $anyRunning = $true
                        break
                    }
                }
                
                if (-not $anyRunning) {
                    Write-Host "Confirmed no Blizzard processes. Reverting TLS..." -ForegroundColor Yellow
                    Disable-LegacyTLS
                    break
                }
            }
            
            Start-Sleep -Seconds 10
        }
    }
    finally {
        # Always revert on exit
        Disable-LegacyTLS
    }
}

# Main execution
if (-NOT ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
    Write-Host "Please run as Administrator!" -ForegroundColor Red
    pause
    exit
}

Monitor-BlizzardProcesses

Method 3: Windows Scheduled Task Automation

Create two tasks that trigger based on [Battle.net](https://battle.net/) process events:
Step 1: Create "Enable Legacy TLS" Task
powershell

# Save as: Create-TLS-Tasks.ps1
# Run once to set up automation

$enableScript = @'
# Enable Legacy TLS
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client" /v Enabled /t REG_DWORD /d 1 /f
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client" /v DisabledByDefault /t REG_DWORD /d 0 /f
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client" /v Enabled /t REG_DWORD /d 1 /f
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client" /v DisabledByDefault /t REG_DWORD /d 0 /f
certutil -setreg chain\ChainMinSHA1PubKeyBitLength 0
net stop CryptSvc /y
timeout /t 1
net start CryptSvc
'@

$disableScript = @'
# Disable Legacy TLS  
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client" /v Enabled /t REG_DWORD /d 0 /f
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client" /v DisabledByDefault /t REG_DWORD /d 1 /f
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client" /v Enabled /t REG_DWORD /d 0 /f
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client" /v DisabledByDefault /t REG_DWORD /d 1 /f
certutil -setreg chain\ChainMinSHA1PubKeyBitLength 1024
net stop CryptSvc /y
timeout /t 1
net start CryptSvc
'@

# Save scripts
$enableScript | Out-File -FilePath "C:\Windows\Temp\EnableLegacyTLS.bat" -Encoding ASCII
$disableScript | Out-File -FilePath "C:\Windows\Temp\DisableLegacyTLS.bat" -Encoding ASCII

# Create task to enable TLS when Battle.net starts
$action = New-ScheduledTaskAction -Execute "C:\Windows\Temp\EnableLegacyTLS.bat"
$trigger = New-ScheduledTaskTrigger -AtLogOn
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries
Register-ScheduledTask -TaskName "Enable Legacy TLS for Gaming" -Action $action -Trigger $trigger -Settings $settings -Description "Enables TLS 1.0/1.1 when Battle.net runs" -RunLevel Highest

Write-Host "Tasks created! Use Method 2's monitoring script for best results." -ForegroundColor Green

Method 4: Fiddler Proxy Interception (Most Secure)

This intercepts ONLY [Battle.net](https://battle.net/) traffic and downgrades TLS:

    Install Fiddler Classic

    Configure FiddlerScript to downgrade TLS only for Blizzard domains:

javascript

// In Fiddler: Rules > Customize Rules
import System;
import System.IO;

class Handlers
{
    static function OnBeforeRequest(oSession: Session) {
        // Only affect Blizzard domains
        if (oSession.HostnameIs("blizzard.com") || 
            oSession.HostnameIs("battle.net") ||
            oSession.HostnameIs("akamaihd.net")) {
            
            // Force TLS 1.0 for these connections
            oSession["x-force-tls1.0"] = "true";
            oSession["x-force-tls1.1"] = "true";
            
            // Override .NET's TLS settings for this session
            oSession["x-override-certvalidation"] = "true";
        }
    }
}

    Configure [Battle.net](https://battle.net/) to use Fiddler as proxy (127.0.0.1:8888)

    Other applications bypass Fiddler and use system TLS settings

Method 5: Docker Container Approach (Advanced)

Run [Battle.net](https://battle.net/) in a container with custom TLS settings:
dockerfile

# Dockerfile
FROM windows:10

# Set legacy TLS settings in container only
RUN reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client" /v Enabled /t REG_DWORD /d 1 /f
RUN reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client" /v Enabled /t REG_DWORD /d 1 /f

# Install Battle.net
ADD Battle.net-Setup.exe .
RUN Battle.net-Setup.exe

Recommendation:

Use Method 2 (PowerScript with monitoring) - it's the most reliable and automatic. Here's a simplified workflow:

    Create shortcut to the PowerShell script on your desktop

    Right-click > Properties > Advanced > Run as administrator (check this)

    Use this shortcut instead of the normal [Battle.net](https://battle.net/) launcher

    The script will:

        Enable legacy TLS when you launch it

        Monitor for any Blizzard processes

        Auto-revert when you close all Blizzard games

        Always revert if you force-close the script

Security benefit: Your system stays secure 99% of the time. TLS 1.0/1.1 is only enabled while gaming, and the script ensures it gets disabled even if you forget.

Want me to help you set up any specific method?
