### ISSUE TITLE
[Bug]: executing powershell scripts?

### ISSUE THREAD

**Issue by TarryDan** [undergroundwires/privacy.sexy#431]
### Description

I'm forgetful, so I use the up arrow to scroll through Powershell to reuse my regularly-used commands. This week, I found code there I hadn't executed, supposedly coming from privacy.sexy, and I'm feeling pretty uncomfy. 

Windows did update this week, , & I can sort of read that the code is doing some kind of tampering with the update process. But I've never seen someone else's code in my terminal before; it didn't ask permission to run; and I also don't remember installing privacy.sexy (tho its not out of character). The folder %APPDATA%\privacy.sexy\runs doesn't seem to exist - i can't find out how to uninstall it, or access the website. Avast reported no problems. But I'm not happy seeing code I didn't expect to see giving itself permission to open powershell with admin privileges. I feel very disquieted.
 
Is this legit? & how do I uninstall and verify that it's uninstalled?

[mystery output.txt](https://github.com/user-attachments/files/17216261/mystery.output.txt)

### Reproduction steps

0. Possibly, start by updating windows
1. Open Powershell 
2. Use the up arrow to view recently used commands
3. observe lines of code I didn't run

### Expected behavior

I expected to see lines of code I had run recently

### privacy.sexy environment details

Neither, as far as I can remember, but I use Windows

**Comment by undergroundwires** [comment]
Starting from `> @echo off`, it looks like privacy.sexy script.
This may be caused by `Run script on startup [EXPERIMENTAL]` script, try reverting it.

The script creates a file at `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\privacy-cleanup.bat`. This makes Windows run it on startup. You can inspect that file to see what you generated historically.

**Comment by undergroundwires** [comment]
No update from OP
