### ISSUE TITLE
[Bug]: Disable Windows Update device driver search reg value is wrong

### ISSUE THREAD

**Issue by LuckyLuke-Oddshot** [undergroundwires/privacy.sexy#444]
### Description

The reg value the "Disable Windows Update device driver search" option adds, is wrong. The `SearchOrderConfig` gets set to `1` when it should be set to `0`.

### How can the bug be recreated?

1. Go to "Disable OS data collection"
2. Under "Disable Windows Update data collection" check the "Disable Windows Update device driver search" option.
3. Note that the `data` PowerShell variable is set to `1` when it should be `0` instead.

### Operating system

Windows 11 IoT Enterprise LTSC

### Screenshots

![Screenshot 2024-10-27 152307](https://github.com/user-attachments/assets/b7a00c2a-4594-4139-9ec1-d5b65011c1e2)

**Comment by undergroundwires** [comment]
You are right.
Source: https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.DeviceSoftwareSetup::DriverSearchPlaces_SearchOrderConfiguration

It will be fixed. Thank you @LuckyLuke-Oddshot ❤️.

Something I was considering before was moving **Disable automatic driver updates by Windows Update** (which contains this script) from its current location:

- Disable OS data collection ➜ Disable Windows Update data collection

to:

- Privacy over security ➜ Disable automatic updates

Would you agree that this is better categorization? My reasoning is that they do not just disable the data collection but also automatic updates themselves to the drivers.

**Comment by LuckyLuke-Oddshot** [comment]
Thank you :), I do agree that moving the setting makes more sense.

**Comment by undergroundwires** [comment]
Fix released as part of [0.13.7](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.7) 🚀. It includes both re-categorization and the fixes. Feel free to test it and open new issue if there are any other issues. Thank you again.
