### ISSUE TITLE
[Bug]: Some Harden Edge Privacy options do not work.

### ISSUE THREAD

**Issue by jarelllama** [undergroundwires/privacy.sexy#455]
### Description

`Block Edge third party cookies` does not enable the `Block third-party cookies` option in Edge. Instead, the option is disabled and cannot be changed.

The same issue happens with `Enable Do Not Track requests`. The `Send "Do Not Track" requests` option in Edge is disabled and cannot be changed.

### How can the bug be recreated?

1. Configure programs > Configure browsers > Configure Edge
2. Enable Block Edge third party cookies
3. Enable Do Not Track requests
4. Run the script
5. Open edge and notice the respective settings are disabled and cannot be changed.

### Operating system

Version 131.0.2903.70 (Official build) (64-bit) on Windows 11

**Comment by undergroundwires** [comment]
Fix released as part of [0.13.7](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.7) 🚀. Feel free to test it and open new issue if there are any other issues. Thank you.
