### ISSUE TITLE
Increase actually version-string size on homepage

### ISSUE THREAD

**Issue by beerisgood** [undergroundwires/privacy.sexy#5]
On your website, the version string is very small for me:
<img width="1086" alt="version" src="https://user-images.githubusercontent.com/9625159/79638634-dbb69c00-8186-11ea-87ba-a8f3f7b617e0.png">

**Comment by undergroundwires** [comment]
Thanks for the feedback @beerisgood  ! I like your attention to details :) Versioning now is a manual process, I'm actually experimenting with automating versioning and also some improvements in deployment. I'll fix the issue & make text bigger and do the automation improvements soon.

**Comment by undergroundwires** [comment]
Hi @beerisgood. I was gonna do some little updates but they became bigger than I expected.. 🤭

During this time I've created some new CI/CD tools [aws-static-site-with-cd](https://github.com/undergroundwires/aws-static-site-with-cd) and [bump-everywhere](https://github.com/undergroundwires/bump-everywhere) for automating this repo in a best way.

Now that versioning and many other things are automated, I made the text bigger and added privacy policy in the last [recent release](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.4.4).

Check it out at: https://privacy.sexy

Feel free to give feedback or close the issue if you feel it's done.

Cheers 🍻

**Comment by beerisgood** [comment]
Looks good to me
