### ISSUE TITLE
0 sized "null" file created after bat run

### ISSUE THREAD

**Issue by necros2k7** [undergroundwires/privacy.sexy#52]
subj

**Comment by undergroundwires** [comment]
Hi @necros2k7 , thanks again for being active and improving the application. I need more information to be able to answer why. There's no intended behavior to create any file. What file is created? What's its full name? Where is it created?

**Comment by necros2k7** [comment]
It`s zero sized file name "null" in directory where bat ran from.

**Comment by undergroundwires** [comment]
You're right it should be `2>nul` not `2>null`. Thanks 🙏🏿
