### ISSUE TITLE
Action bar, wifi window cannot be accessed after running a script

### ISSUE THREAD

**Issue by vachan-maker** [undergroundwires/privacy.sexy#55]
These scripts are great and with it I uninstalled the windows apps, onedrive and disabled telemetry. But the wifi pop up window cannot be accessed. I don't know which script reverts the change
This is the window and it does not appear
![image](https://user-images.githubusercontent.com/65799568/107146781-47fdc880-6970-11eb-9950-4b7263a30252.png)

**Comment by vachan-maker** [comment]
Sorry to disturb,
I went through a bunch of scripts and reverted many. But still I don't know which script disabled the action centre, battery pop up window, wifi window.

**Comment by undergroundwires** [comment]
Hi @vachan-maker , I'm sorry that I did not understand what's getting disabled exactly.

What exactly is the "wifi pop up window"? In the screenshot you can see the WiFi icon, and can click on it, so what is the problem? When you say battery pop up window and action centre, do you mean that the icons are missing or it does not work if you click on them?

It would also be helpful if you could share the script you generated and your Windows version.

**Comment by vachan-maker** [comment]
> 
> 
> Hi @vachan-maker , I'm sorry that I did not understand what's getting disabled exactly.
> 
> What exactly is the "wifi pop up window"? In the screenshot you can see the WiFi icon, and can click on it, so what is the problem? When you say battery pop up window and action centre, do you mean that the icons are missing or it does not work if you click on them?
> 
> It would also be helpful if you could share the script you generated and your Windows version.

Its my fault for not writing clearly. The screenshot is just for reference. 
The problem:
The WiFi pane or popup shown in the above image does not appear at all when I click the wifi icon/symbol on the taskbar. This is the same case with the battery popup or pane. 

I used these scripts
- Uninstall all the windows apps. It even removed the Windows Defender and Settings. 
- Uninstall OneDrive and remove leftover files
- Disable some windows telemetry.
 **I have no clue which scripts reverts the problem. I looked many times but didn't find it**
Thanks for your help.

**Comment by undergroundwires** [comment]
Thanks. Now I understand, so you have the icons on taskbar but panes do not appear i.e. clicking on them do not anything.

My initial guess is that disabling windows telemetry and OneDrive should not have any affect them. It's most likely that uninstalling all the windows apps has caused it. I'll remove those apps from bloatware section once we identify them.

Do you have the the exact script that was generated from privacy.sexy? If you have the scripts and can provide me your windows version I can try to reproduce it.

**Comment by undergroundwires** [comment]
Hi @vachan-maker , I'm sorry that I did not understand what's getting disabled exactly.

What exactly is the "wifi pop up window"? In the screenshot you can see the WiFi icon, and can click on it, so what is the problem? When you say battery pop up window and action centre, do you mean that the icons are missing or it does not work if you click on them?

It would also be helpful if you could share the script you generated and your Windows version (you can find it using "Start button" > "Settings" > "System" > "About").

Btw I just deleted my last comment by mistake...

**Comment by vachan-maker** [comment]
I am sorry for making this confusing. I removed the screenshot tools, game bar, etc from my machine. So I was kind of lazy to download an additional software for taking a screenshot.

**I downloaded the above image from some website.** Sorry for not making that clear.
**Problem**
**The wifi pane/popup - that long rectangular pane with the name of the wifi networks doesn not appear at all when clicking on it. This is the same case with the battery pop up.

**Actual video of the situation** 

https://user-images.githubusercontent.com/65799568/108066017-cc44ff80-7084-11eb-9071-641567d10a06.mp4

**Comment by vachan-maker** [comment]
Any updates on this issue?

**Comment by mikhoul** [comment]
I'm pretty sure it's a service that has been disabled,

IMO the best way to fix your issue is to revert the services to their default one by one to find which service have the offending setting.

You can do it manually by looking at this list of Services default here: https://www.tweakhound.com/2020/12/23/windows-10-default-services-v20h2/

Or you can use those .REG files in the attachement: 
[Windows_10_default_services.zip](https://github.com/undergroundwires/privacy.sexy/files/6037229/Windows_10_default_services.zip)

Regards :octocat:

**Comment by undergroundwires** [comment]
It can also be caused by deleting Settings app. It's not a bloatware at all, I'm removing that tweak from privacy.sexy. Can you try to revert the settings app tweak? If it still does not work, you could go to `Uninstall system apps` and revert them one by one. Please share if you can figure out a solution for it so we can remove tweak that's causing it from privacy.sexy.

**Comment by vachan-maker** [comment]
Thanks @undergroundwires and @mikhoul for the help
I just found the script and reverted it. 
This is the script called **Start App**

```
@echo off
:: https://privacy.sexy — v0.9.1 — Fri, 26 Feb 2021 01:36:01 GMT
:: Ensure admin privileges
fltmc >nul 2>&1 || (
    echo Administrator privileges are required.
    PowerShell Start -Verb RunAs '%0' 2> nul || (
        echo Right-click on the script and select "Run as administrator".
        pause & exit 1
    )
    exit 0
)


:: ----------------------------------------------------------
:: --------------------Start app (revert)--------------------
:: ----------------------------------------------------------
echo --- Start app (revert)
PowerShell -Command " $package = (Get-AppxPackage -AllUsers 'Microsoft.Windows.ShellExperienceHost'); if (!$package) { Write-Error 'App could not be found' -ErrorAction Stop; } $directories = @($package.InstallLocation, \"$env:LOCALAPPDATA\Packages\$($package.PackageFamilyName)\"); foreach($dir in $directories) { if ( !$dir -Or !(Test-Path \"$dir\") ) { continue; } cmd /c ('takeown /f \"' + $dir + '\" /r /d y 1> nul'); if($LASTEXITCODE) { throw 'Failed to take ownership'; } cmd /c ('icacls \"' + $dir + '\" /grant administrators:F /t 1> nul'); if($LASTEXITCODE) { throw 'Failed to take ownership'; } $files = Get-ChildItem -File -Path \"$dir\*.OLD\" -Recurse -Force; foreach($file in $files) { $newName = $file.FullName.Substring(0, $file.FullName.Length - 4); Write-Host \"Rename '$($file.FullName)' to '$newName'\"; Move-Item -LiteralPath \"$($file.FullName)\" -Destination \"$newName\" -Force; } };"
:: ----------------------------------------------------------


pause
exit /b 0
```
