### ISSUE TITLE
Enhancement - Win 10 Customizing

### ISSUE THREAD

**Issue by usamac** [undergroundwires/privacy.sexy#56]
No issues at all that I have run into. So far, I am absolutely loving this script builder!

Is there any chance there could be an added section to customize and/or add applications like alternative browsers, zip managers, pdf readers, Malwarebytes, everything (app), etc

It would also be great to allow for the customization of the the start menu and/or settings menu in the notifications bar.

One last time, I just want to express how awesome project is and how excited I am to see future developments to it! Thank you for all your hard work!

**Comment by mikhoul** [comment]
> Is there any chance there could be an added section to customize and/or add applications like alternative browsers, zip managers, pdf readers, malwarebytes, everything (app), etc
> 
> It would also be great to allow for the customization of the the start menu and/or settings menu in the notifications bar.


I agree an support it !

**Comment by undergroundwires** [comment]
Hi,

Thanks for your very nice feedback @usamac . It's heartwarming 😊

I think all of your ideas sound good and exciting. I'm open to having them in our script list. Let's refine them and specify them to get started.

**Adding applications**: A section like "install privacy friendly apps" would be nice. I suspect that it might be tricky as there's no global way of installing software but if anyone can provide scripts to install a few applications that enhances or respects privacy, I'd be happy to merge it / add them.

New scripts for customizations sound nice. Are we talking about privacy-related or non-privacy related customizations? If they are related to privacy we could add them under "Configure programs" (to configure third party software) or under "UI for privacy".

**Comment by mikhoul** [comment]
> . Are we talking about privacy-related or non-privacy related customizations?

It could be both, often customisation and privacy overlap on each other. 

Things/tweaks more oriented toward customisation and power-users could be listed in a new section, something called like "Advanced custom Tweaks" or something like that.

Regards :octocat:

**Comment by undergroundwires** [comment]
I've been against the idea of blending in non-privacy stuff as I considered it out of scope. But as the interest is mentioned a few times, maybe we should just try it out.

A consideration I have is how we can handle those without alienating people here for privacy & security only which is the solution is built for. Let’s consider a use-case:

> I'd like to test a malware in a forensics lab. I choose “All” tweaks on top aiming for maximized privacy

If we start adding other types of customizations then that person would get a lot of stuff with "personal taste” that he does not wish to nor expect to from a privacy enhancing app. I wonder how we can address it in our solution.

Some potential solutions:

- As you suggest we create new category like “Advanced custom tweaks". But then we exclude that category from selection when user selects “All”.
- Fork this repository, create a new app like "tweak store" where we only have those scripts.
- Create a new collection. Today we have “Windows” and “macOS” collection. We could also introduce “Windows (non-privacy)” so in the end we’d end up with : • Windows • Windows (non-privacy) • macOS on top menu.

Do we have more options? What do you think? Which option sounds most viable?

Looking forward to your feedback.

**Comment by mikhoul** [comment]
> * As you suggest we create new category like “Advanced custom tweaks". But then we exclude that category from selection when user selects “All”.

I thinks this way is the best, for users looking only for privacy tweaks it will be easy with 2 distincts category it will be easy to only choose one category.

Also for the "buttons" it could be something in the like of:

_Select:_ 
 **_Privacy enhancement_**:  None | Standard | Strict | All 
              **_Others custom Tweaks for Power-Users_**:  None | Standard | Strict | All 
              
------------------------------------------------------------------------------------------
              
Since tweaks of différents category often overlap we could TAG tweaks in different category and even sub category.

Example a Tweak: A tweak named Tweak123 that disable a service for privacy reason could have more than one tag tags like:  Memory saving + Privacy related.

This way what would make the tweak show up in one section or in both section would be the tags attached to them.

Also integrating tags it would allow (if we want) to classify more granularly tweaks like: Visual tweaks, memory savers, CPU Tweaks,  External Software configurations,  contextual menu etc etc..

Creating a new collection would not be good because usually power-users will like to have an easy access to all tweaks available in the same place and people who install powershell scripts are more susceptible to be power-users than casual users.

**Comment by undergroundwires** [comment]
Thanks for your input again. Your suggestions are really appreciated and shape the future of the project 🤟🏿

**Quick solution**

I think we found a nice way to start. We add a new category, maybe change its color in UI slightly so it stands out from other categories, and exclude it from "All, Standard, Recommended".

So feel free post what custom tweaks (non-privacy related) you'd like to see here. Revert scripts for the tweaks would much appreciated.

I'll add them to the app when we have a few of them. 

**Better solution**

It seems like tagging is best way to go forward here. It's easy to implement and gives much more granularity as in your examples. Your observation is right, categories often overlap and does not make what's going on very clear. Existing privacy scripts also benefit a lot from tags. So there's big value in tags.

I think it would be hard for defining what "standard" and "strict" is for **Others custom Tweaks for Power-Users**. "All" would also not make a lot of sense for all custom tweaks. So I don't think that those should follow the same recommendation levels as privacy ones. Actually I think we could convert existing recommendation levels to tags like: "privacy-standard", "privacy-strict", "privacy-all".  Then power-user scripts can live outside of those tags.

So I think we agree that tags is the future here. It's also not so hard to implement.

**Comment by undergroundwires** [comment]
Thanks for your input again. Your suggestions are really appreciated and shape the future of the project 🤟🏿

**Quick solution: "special category"**

I think we found a nice way to start. We add a new category, maybe change its color in UI slightly so it stands out from other categories, and exclude it from "All, Standard, Recommended".

So feel free post what custom tweaks (non-privacy related) you'd like to see here. Revert scripts for the tweaks would much appreciated.

I'll add them to the app when we have a few of them. 

**Better solution: "tags"**

It seems like tagging is best way to go forward here. It's easy to implement and gives much more granularity as in your examples. Your observation is right, categories often overlap and does not make what's going on very clear. Existing privacy scripts also benefit a lot from tags. So there's big value in tags.

I think it would be hard for defining what "standard" and "strict" is for **Others custom Tweaks for Power-Users**. "All" would also not make a lot of sense for all custom tweaks. So I don't think that those should follow the same recommendation levels as privacy ones. Actually I think we could convert existing recommendation levels to tags like: "privacy-standard", "privacy-strict", "privacy-all".  Then power-user scripts can live outside of those tags.

**Comment by mikhoul** [comment]
> So feel free post what custom tweaks (non-privacy related) you'd like to see here. Revert scripts for the tweaks would much appreciated.
> 
> I'll add them to the app when we have a few of them.

Which place would be the best to post them ?

I ask this question so that the scripts are not all scattered around and that it is more difficult for you to group them together to integrate them later.

Regards !

**Comment by undergroundwires** [comment]
Thanks for asking and also suggesting a much better way of working in your question 🙏🏽!

Yeah it usually gets chaotic when combining many requests as you've already seen 😀

Creating PRs is not a good option now when we don't have a category/structure for those tweaks yet so I think we should create a new issue per tweak wished. I'll create a special issue template for tweak suggestions later on but for now I think creating a new issue with "blank issue template" (on bottom) is good.

As we have a good plan and made the decisions I'm closing this issue and we continue future issues per tweak.
