### ISSUE TITLE
Problems with microphone input and establishing SSL/TLS connections

### ISSUE THREAD

**Issue by CodingArctic** [undergroundwires/privacy.sexy#57]
### Describe the bug

I just used the script, didn't choose any crazy options. but now no programs get input from my mic? I need to do zoom classes, and this is kind of a big problem. 

### OS

windows 10 20h2 19042.746

### Scripts

[privacy-script.zip](https://github.com/undergroundwires/privacy.sexy/files/5953283/privacy-script.zip)

this was the script i ran (in zip form cause i cant upload .bat)

### To Reproduce

Steps to reproduce the problem:

**Comment by CodingArctic** [comment]
this resolved itself?? also having another issue where my image is failing to upload in ShareX (my screenshotting program)

![image](https://user-images.githubusercontent.com/16868830/107407519-c163fb00-6ad7-11eb-94e3-42c6de3c4250.png)

**Comment by undergroundwires** [comment]
Hi @CodingArctic, it's probably `Deny app access to microphone` script. It should be solved if you revert it by searching for it, clicking on "revert" next to it and run the generated script.

**Comment by undergroundwires** [comment]
Hi @CodingArctic,

For first problem: it's probably `Deny app access to microphone` script as Zoom is probably . It should be solved if you revert it by searching for it, clicking on "revert" next to it and run the generated script. I'll add a warning icon next to those "breaking" scripts just to make it more clear.

For second problem: it seems like ShareX is using insecure protocols ShareX/ShareX#4518 . You may want to revert "SMBv1 protocol" script and "Increase cryptography on ISS" category. However those protocols are deprecated, insecure and have known vulnerabilities enabling different attacks.

**Comment by undergroundwires** [comment]
Hi @CodingArctic,

For first problem: it's probably `Deny app access to microphone` script as Zoom is probably . It should be solved if you revert it by searching for it, clicking on "revert" next to it and run the generated script. I'll add a warning icon next to those "breaking" scripts just to make it more clear.

For second problem: it seems like ShareX is using insecure protocols (see ShareX/ShareX#4518). You may want to revert "SMBv1 protocol" script and "Increase cryptography on ISS" category. However those protocols are deprecated, insecure and have known vulnerabilities enabling different attacks.

**Comment by undergroundwires** [comment]
Closing this as this is not a bug caused by privacy.sexy but a problem with the project where it uses insecure protocol. I'd be happy if you could get back on whether the reverting the scripts mentioned in my last comment has solved your problem or re-open the issue if any additional help is needed.

**Comment by undergroundwires** [comment]
I've reworked network-related scripts completely in [0.13.3](https://github.com/undergroundwires/privacy.sexy/releases/edit/0.13.3), it should solve this issue along with others.
