### ISSUE TITLE
[BUG]: Unable to change PIN and Password

### ISSUE THREAD

**Issue by SSimpl3** [undergroundwires/privacy.sexy#67]
### Describe the bug
Go to Settings > Sign-in Options
The only options are Security Key
I've previously set up PIN and Password for different account, after using this script, I noticed the option to change PIN and Pass were gone

### OS
Windows 10 Pro 2004 19041.867

### Screenshots
![image](https://user-images.githubusercontent.com/53003695/113510938-73272180-9587-11eb-967e-b4ef68df4fa1.png)

### Scripts
[debloat.txt](https://github.com/undergroundwires/privacy.sexy/files/6254651/debloat.txt)

### Additional information
I'm using 0.10.1 version of privacy.sexy
If the warning for the script that caused this then please apply a warning for it

**Comment by undergroundwires** [comment]
Hi @SSimpl3 , I've tested this and it's still also reproducible on Windows 10 21H1.

This happened to be same problem as #64 .

Unfortunately it was privacy.sexy script that has caused it.

Reverting `Cloud Experience Host app` would fix the issue for you.

The behavior will be documented with a warning as you suggest, it will also be removed from recommendation pool. Thanks for mentioning this.

**Comment by undergroundwires** [comment]
Hi @SSimpl3 , I've tested this and it's still also reproducible on Windows 10 21H1.

This happened to be same problem as #64 .

Unfortunately it was privacy.sexy script that has caused it.

Reverting `Cloud Experience Host app` would fix the issue for you.

The behavior will be documented with a warning as you suggest.

**Comment by undergroundwires** [comment]
I tested this and it's still also reproducible on Windows 10 21H1.

This happened to be same problem as #64 .

Unfortunately it was privacy.sexy script that has caused it.

Reverting `Cloud Experience Host app` would fix the issue for you.

The behavior will be documented with a warning as you suggest.

**Comment by undergroundwires** [comment]
I tested this and it's still also reproducible on Windows 10 21H1.

This happened to be same problem as #64 .

Unfortunately it was privacy.sexy script that has caused it.

Reverting `Cloud Experience Host app` would fix the issue for you.

**Comment by undergroundwires** [comment]
I tested this and it's still also reproducible on Windows 10 21H1.

This happened to be same problem as #64 .

Unfortunately it was privacy.sexy script that has caused it.

Reverting `Cloud Experience Host app` would fix the issue for you.

Following your suggestion, better documentation will be added and I'll also remove it it from Strict recommendation list until a better warning mechanism is implemented.

**Comment by undergroundwires** [comment]
This app is documented and unrecommended for a while now.
