### ISSUE TITLE
[BUG]: Search Reversing

### ISSUE THREAD

**Issue by owersite** [undergroundwires/privacy.sexy#76]
Hello, i used to disable Search windows feature but when i reversed i did not get it back, what do i do?

**Comment by undergroundwires** [comment]
Hi, thanks for the bug report.

Could you run `Dism /Online /Get-FeatureInfo /FeatureName:"SearchEngine-Client-Package"` on a command line and share what you see? It would give us more insights about what the problem is.

P.S.: It may require reboot to get the service back.

**Comment by owersite** [comment]
Sure! I already did that and got error but never screen-shotted it, ill do it real quick now.

**Comment by owersite** [comment]
By the way, my search bar opens, but when i search in like lets say "Discord" nothing happens or anything else than Discord, maybe spotify etc. This command now worked, here you go picture that i got no errors,  https://pays.host/67Sx3Mkt
but problem i have is still not fixed.

**Comment by undergroundwires** [comment]
🤔 Search feature seems to be running. So the issue must be somewhere else. It can be `Search app` script that's known to break search, maybe try to revert that one if you had it.

To troubleshoot it more and reproduce could you attach the generated script that you executed and also attach a screenshot to illustrate what you mean i.e. the expected behavior vs the actual?

**Comment by owersite** [comment]
You want me to send you my privacy.bat script i used? I have it on pc if u need i will

**Comment by undergroundwires** [comment]
@owersite , yes please attach the file and also add a screenshot of the wrong behavior.

**Comment by owersite** [comment]
![image](https://user-images.githubusercontent.com/60113773/117704743-7edfb680-b1cb-11eb-8312-0a48c653ebaf.png)

**Comment by owersite** [comment]
Help?

**Comment by undergroundwires** [comment]
@owersite Bumping here would not be beneficial without required information to reproduce. This is why bug issue template exists which you did not use and it's the reason we're wasting time here by having Q&A to provide answers to questions that should have been answered in first place. Please share your OS version and attach your script file.

**Comment by undergroundwires** [comment]
Bumping here would not be beneficial without required information to reproduce. This is why bug issue template exists which you did not use and it's the reason we're wasting time here by having Q&A to provide answers to questions that should have been answered in first place. So feel free to share your OS version and attach your script file.

**Comment by owersite** [comment]
These scripts are bullshit, i reinstalled into a modded version of windows without bloatware and yea, not need to fuck with this anymore, cya.
