### ISSUE TITLE
Obsolete policies 

### ISSUE THREAD

**Issue by hjk4** [undergroundwires/privacy.sexy#78]
The 2 policies below are obsolete as of Edge 89. I'd also suggest the removal of policies that refer to Edge legacy, since it's no longer supported

![Captura de ecrã 2021-05-10 134704](https://user-images.githubusercontent.com/83961303/117662551-9604b100-b197-11eb-8ced-6dd108ac636e.png)

**Comment by undergroundwires** [comment]
Thanks for the feedback! There may be people who are still using the older edge chromium and would like to apply the policies. How would you suggest we address it something like this and allowing them to use the scripts?

**Comment by undergroundwires** [comment]
I'm closing this. We keep the obsolete policies in privacy.sexy for people who's running the obsolete versions. Those configs would not have any bad impact on people running the newer versions. Please re-open this if you can concretize how we should approach the issue in a better way.
