### ISSUE TITLE
[BUG]: Error on executing Disable NetBios for all interfaces

### ISSUE THREAD

**Issue by jebr** [undergroundwires/privacy.sexy#80]
### Describe the bug
I get an error when running the Disable NetBios for all interfaces.

Error message:
`The string is missing the terminator: ".
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString` 

### OS
Edition: Windows 10 Pro
Version: 20H2
Build: 19042.1052

### Screenshots

![afbeelding](https://user-images.githubusercontent.com/7726815/121670377-a61cf280-caad-11eb-8aab-3d3cb7664a61.png)

### Scripts
Script is generated by privacy.sexy

`:: ----------------------------------------------------------
:: ------------Disable NetBios for all interfaces------------
:: ----------------------------------------------------------
echo --- Disable NetBios for all interfaces
PowerShell -ExecutionPolicy Unrestricted -Command "$key = 'HKLM:SYSTEM\CurrentControlSet\services\NetBT\Parameters\Interfaces'; Get-ChildItem $key | foreach { Set-ItemProperty -Path \"$key\$($_.pschildname)\" -Name NetbiosOptions -Value 2 -Verbose }"
:: ----------------------------------------------------------`

**Comment by undergroundwires** [comment]
Hi @jebr , thanks for a clear bug report, you're running the script using PowerShell terminal which treats double quotes differently than `cmd` (batch) terminal. Privacy.sexy uses batch terminal as it's more widely available so try it using `cmd` and it would work.

**Comment by jebr** [comment]
You're right. When I run the completely generated in cmd I don't get an error and the registry keys are modified.
Thanks for your reply.

**Comment by undergroundwires** [comment]
Closing the issue then, thanks for the reporting back the results
