### ISSUE TITLE
MacOS: Add script to disable Gatekeeper and XProtect

### ISSUE THREAD

**Issue by AnonymousPlanet** [undergroundwires/privacy.sexy#83]
### Problem Description

The site doesn't mention Gatekeeper privacy issues. Query the database by issuing: 

`echo 'SELECT datetime(LSQuarantineTimeStamp + 978307200, "unixepoch") as LSQuarantineTimeStamp, ' \
  'LSQuarantineAgentName, LSQuarantineOriginURLString, LSQuarantineDataURLString from LSQuarantineEvent;' | \
  sqlite3 /Users/$USER/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV2`

### Proposed solution

Add script to disable Gatekeeper and XProtect

### Alternatives considered

Add script to remove Gatekeeper/Quarantine attributes from files and clean the Quarantine database:

To clear database:
`:>~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV2`

To prevent further database usage:

`sudo chflags schg ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV2`

Disable Gatekeeper service:

`sudo spctl --master-disable`

Remove Quarantine attributes from file:

`xattr -d com.apple.metadata:kMDItemWhereFroms filename`
`xattr -d com.apple.quarantine filename`

**Comment by undergroundwires** [comment]
This is great. Thank you for the context and clean and clear scripts. A perfect contribution. I'll add it in the next minor version that I plan to release in a month.
