### ISSUE TITLE
some useful patches

### ISSUE THREAD

**Issue by playgithub** [undergroundwires/privacy.sexy#86]
[patch.zip](https://github.com/undergroundwires/privacy.sexy/files/6973155/patch.zip)

**Comment by undergroundwires** [comment]
Thank you!

- `VS16NoTelem.bat`: Already exists
- `del_3D_Objects_Lib.cmd`: Does not contribute to privacy. I have it roadmap to support scripts not related to privacy, however this is not on-place now.
- `disable_active_probing.reg`: Already exists

I will add `disable_windows_feeds_about_weather_and_news.reg` in upcoming version.

Let me know if there's anything more we're missing from Windows 10 June 2021 that we should configure.

P.S. Your contribution is appreciated and welcomed. I hope you come come up with more. I would be extra happy if you could provide scripts, their revert code and some more context/references. I just added a new issue template for suggesting new scripts or a PR with requested metadata would be appreciated also, [updated documentation](https://github.com/undergroundwires/privacy.sexy#extend-scripts) about it.

**Comment by playgithub** [comment]
I'd like to contribute to the project.
I'll study it, and do PR.
Thanks very much
