### ISSUE TITLE
Some installer failed to installer

### ISSUE THREAD

**Issue by playgithub** [undergroundwires/privacy.sexy#89]
On a newly installed Windows 10 pro, select mode `Strict`, tweak a little, apply.
After that, some installers fails to install, screenshot as below, how to recover?
![Capture](https://user-images.githubusercontent.com/3665590/130638573-6a13a566-3d2c-469d-988f-294e5730de4c.PNG)

When run the installer in a terminal window with admin priviledge, it succeedes.

**Comment by undergroundwires** [comment]
Hi @playgithub , thanks for the bug report. Sad that it somehow intervened with the installation. But there needs to be more information to be able to take action.

Please attach the scripts you executed, and other required information such as OS version. If it cannot be reproduced, it cannot be fixed. I recommend using the [issue template](https://github.com/undergroundwires/privacy.sexy/issues/new/choose) for bug reporting scripts that prompts you these kind of information.

Also logs from the windows installer would be very helpful for faster diagnosis/help.

**Comment by undergroundwires** [comment]
Hi @playgithub , thanks for the bug report. Let's track this down and fix it.

1. Could you provide logs from windows installer? See [here](https://superuser.com/questions/180281/what-folder-are-installation-logs-in/853773#853773) for a nice way to get the logs.

2. Please provide the script you executed, and share your OS version.

**Comment by playgithub** [comment]
The failed installer might be either .exe or .msi.
For python it is exe, I've uninstalled it, and reinstall `python-3.9.6-amd64.exe /log log.txt` in terminal without admin priviledge, it succeeds. I think it might only fail for the first time, because it needs some priviledge to initialize something.

OS: Windows 10 Pro 21H1 19043.1165

I'll open another issue when I can't get the log with failures.

Thanks

**Comment by playgithub** [comment]
```
λ msiexec.exe /i .\LibreOffice_7.1.6_Win_x64.msi /L*v install.log
λ cat install.log
□□=== Verbose logging started: 10/1/2021  09:46:26  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\Windows\system32\msiexec.exe ===
MSI (c) (D0:8C) [09:46:26:966]: Font created.  Charset: Req=0, Ret=0, Font: Req=, Ret=Arial

MSI (c) (D0:8C) [09:46:26:966]: Font created.  Charset: Req=0, Ret=0, Font: Req=, Ret=Arial

MSI (c) (D0:9C) [09:46:26:966]: Resetting cached policy values
MSI (c) (D0:9C) [09:46:26:966]: Machine policy value 'Debug' is 0
MSI (c) (D0:9C) [09:46:26:966]: ******* RunEngine:
           ******* Product: .\LibreOffice_7.1.6_Win_x64.msi
           ******* Action:
           ******* CommandLine: **********
MSI (c) (D0:9C) [09:46:26:966]: Machine policy value 'DisableUserInstalls' is 0
MSI (c) (D0:9C) [09:46:26:981]: Note: 1: 1324 2: . 3: 1
MSI (c) (D0:9C) [09:46:26:981]: MainEngineThread is returning 2
=== Verbose logging stopped: 10/1/2021  09:46:26 ===
```

**Comment by playgithub** [comment]
Windows 10 21H2 Build 19044.1586
privacy.sexy 0.11.4 (option Standard)

<img width="804" alt="installer_problem" src="https://user-images.githubusercontent.com/3665590/162349782-4a8fe8dd-1d64-4b89-84f3-79a856683e2e.png">

**Comment by playgithub** [comment]
By allowing the current user to modify and write to `C:\Windows\temp`, the problem is solved.
Which script causes the problem?

**Comment by freighttt** [comment]
i also had the same issue. it seems something is deleting C:\windows\temp 

im sorry im not more proficient in the background processes etc, but i used the "standard" set of scripts, using the offline installer.

creating a new temp folder was the fix.

**Comment by undergroundwires** [comment]
Thank you for the report @freighttt and @lintonf ,

So then it's this script causing the problem:

```yaml
name: Clear Windows temp files
recommend: standard
code: |-
  del /f /q %localappdata%\Temp\*
  rd /s /q "%WINDIR%\Temp"
  rd /s /q "%TEMP%"
```

And  this PR #176 by @iam-py-test seems to resolve this issue. So I'll ensure that PR is merged in upcoming patch releases. We can track the status there.
