### ISSUE TITLE
Do you feel pressure from the company ever?

### ISSUE THREAD

**Issue by playgithub** [undergroundwires/privacy.sexy#91]

**Comment by undergroundwires** [comment]
Hi, we have not been approached by any company officially yet. No threats but no sponsorships/ads etc. either. But small things happen. Bing search engine somehow refuse to index https://privacy.sexy regardless of my efforts. I believe that we have been blacklisted.

In world we live in, intruding others' privacy allows companies to make more money, governments to gain more control, and enable others to offer proprietary closed-source solutions to sell services around it. It's a dark world where initiatives like privacy.sexy disturb many that sit on power. But it should be up to individuals to decide how much data they're willing to share and it's a basic human right to choose not to share data. On a positive note, community appreciated the project, people like you gather around the idea and we collectively contribute to making the project better. The community support and interest is the only reason I keep maintaining the project and will keep doing so.

So thank you for being active, and being with us.

**Comment by playgithub** [comment]
Thanks very much

My pleasrue for contributing
