### ISSUE TITLE
After apply some patches, shadowsocks not work, any clue?

### ISSUE THREAD

**Issue by playgithub** [undergroundwires/privacy.sexy#92]

**Comment by undergroundwires** [comment]
Could you attach the generated script you applied?

**Comment by undergroundwires** [comment]
Could you attach the generated script you applied?

P.S.: When you create a new issue, if you select [Bug report (script bug or unexpected script behavior)](https://github.com/undergroundwires/privacy.sexy/issues/new?assignees=&labels=bug&template=1-bug-report-scripts.md&title=%5BBUG%5D%3A+) it would give much more context that would be useful.

**Comment by playgithub** [comment]
I reinstalled shadowsocks, surprisingly it works. It is its own problem.
Thanks all the same.
