### ISSUE TITLE
Need for patch status

### ISSUE THREAD

**Issue by playgithub** [undergroundwires/privacy.sexy#93]
* status for each patch, e.g.
  * unused
  * patch succeded
  * patch failed
* list patches by status

With this feature, it'll be at a good position for improvement

**Comment by undergroundwires** [comment]
Hi, would you be more specific and elaborate more on the idea with examples/screenshots etc. Good information to add is given in "Feature request" template when you create a new issue:

 Copy pasting template here:
 
 ```markdown
 
 ### Problem description

<!--
What are we trying to solve?
Please add a clear and concise description of the problem you are seeking to solve with this feature request.
E.g. I'm always frustrated when [...]
-->

### Proposed solution

<!--
Describe the solution you'd like in a clear and concise manner.
-->

### Alternatives considered

<!--
A clear and concise description of any alternative solutions or features you've considered.
-->

### Additional information

<!--
If applicable, add any other context or screenshots about the feature request here.
-->

```

**Comment by playgithub** [comment]
### Problem description

It can't be checked taht if a patch is:
* patched successfully
* patched unsuccessfully
* never patched

### Proposed solution

show the status of a patch in "Problem description".
When a problem occurs, based on the status of every patch, it's much easier  test patches one by one to find out the problematic patch.

**Comment by undergroundwires** [comment]
Thanks for more information. As I understand you mean like for each script we have we show a message with for different states such as: "success", "error" "not needed"?

I love the idea. Some scripts do that now meanwhile some do not. Checking if a script is needed to apply i.e. running queries requires even more effort but it would be very nice.

If anyone in community would send any improvements with PR's I'd happily merge them. File to improve is [windows.yaml](https://github.com/undergroundwires/privacy.sexy/blob/0.10.3/src/application/collections/windows.yaml) and it would be pretty easy to improve existing scripts.

For error/success statuses, I've been thinking about running each script in a separate shell. It would increase security by providing better script isolation and also would help with your suggestion: logging error/success messages in a unified way by checking the exit code. 

We already run each PowerShell script in an isolated way by running `PowerShell -Command ""`.  So we could improve [`RunPowerShell`](https://github.com/undergroundwires/privacy.sexy/blob/0.10.3/src/application/collections/windows.yaml#L4513-L4516) function with something like:

```batchfile
PowerShell -Command "..."
if errorlevel 1 (
   echo Script failed, error code: %errorlevel%
) else (
   echo Script run successfully
)
```

For other scripts (bash and batchfile) we could also do similar. For batch let's say that we're calling `reg add "HKLM\Software\Test" /v "Test" /d 1 /f`. We could instead do  something like:

```batchfile
cmd /c "reg add """"HKLM\Software\Test"""" /v "Test" /d 1 /f"
if errorlevel 1 (
   echo Script failed, error code: %errorlevel%
) else (
   echo Script run successfully
)
```

Same can be applied using `bash -c` for macOS scripts. This way we can check status code for each and improve sandboxing. The script generation, inlining and escaping can be automatized. I'm working on that in #53 for just PowerShell scripts, but that work can be extended for batchfile/bash.

The only downside of running scripts in separate subshells and generating scripts like this is that we lose simplicity of generated code. Generated script would more complicated and less human readable when everything is inlined and escaped. But it's a trade-off between more stability/better unified status logging vs readability. 🤔

**Comment by playgithub** [comment]
I think System APIs instead of scripts can achieve better user experience.
If patches can be abstracted in some fixed forms, e.g.
```json
{
  type: registry
  key: HKLM\Software\Test\Telemetry
  option_values: [ "on", "off"]
  value:  "on"
  resetted: true
  compatibility_info: ...
  descriptions: ...
}
```

After patching properly, the application can remember status for every patch in database.
Not surprisingly if a patch is resetted automatically (e.g. by upgrading or resetted by the company) or not valid anymore.
By refreshing, the application can highlight the unexpected changes.

Just for discussing, it needs a lot of work, though it deserves for privacy.

**Comment by undergroundwires** [comment]
I think this is a pretty good idea. As you say it would take very long time today as we don't have many contributors and no one earns money from here, but it's not a blocker. I'd love to discuss more.

So let's say that the user selects `off` value from your example. Then we store that `user wants this registry value off`. Then the application listens to these changes or (or scans periodically) and then when it detects a deviation from the desired state, it notifies the user.

Then maybe we can use the generated script file as the database for the desired state information, and then we do not need to store data elsewhere. I'm actually implementing import/export so we'll eventually have some kind-of machine readable data in script file which will be easier for privacy.sexy to read the file.

What we need to implement this is some kind of query mechanism. For the example before, a query to check if registry is still off so we can know that if we're on the baseline. Same query logic can be used for my other post here as well, so patches are only applied if necessary.

Maybe a new property for each script in [collection files](https://github.com/undergroundwires/privacy.sexy/tree/0.10.3/src/application/collections) where we define a new property like `audit` or `query`:

```yaml
code: reg add HKLM\\Software\\Test\\Telemetry /v "on"
revertCode: reg add HKLM\\Software\\Test\\Telemetry /v "off"
query: script that exits with positive status code if HKLM\\Software\\Test\\Telemetry has "on" value
```

About the abstraction idea. I've been working lately to improve templating with [functions](https://github.com/undergroundwires/privacy.sexy/blob/master/docs/templating.md) for code reusability that may provide the abstraction you're talking about. This way we would not need to implement state checking (`req query`) in each script but in a single function.

F.Y.I: Very basic implementation is idea is [`Run script on start-up`](https://github.com/undergroundwires/privacy.sexy/blob/0.10.3/src/application/collections/windows.yaml#L4382-L4386) script, but it's not as smart as what we're talking.
