### ISSUE TITLE
[BUG]: Info Message

### ISSUE THREAD

**Issue by playgithub** [undergroundwires/privacy.sexy#94]
When execute scripts from GUI, it always shows as below, what about the first 2 lines?
```shell
'ttps:' is not recognized as an internal or external command,
operable program or batch file.
--- Text messaging (revert)
[SC] ChangeServiceConfig SUCCESS
Press any key to continue . . .
```

**Comment by undergroundwires** [comment]
Hi, can you please attach the whole script file or logs?

**Comment by playgithub** [comment]
It seems that every script will display `'ttps:'` at first.
One example below, which it to remove `Microsoft.Appconnector`
## Script
```shell
@echo off
:: https://privacy.sexy — v0.10.3 — Sat, 04 Sep 2021 02:08:38 GMT
:: Ensure admin privileges
fltmc >nul 2>&1 || (
    echo Administrator privileges are required.
    PowerShell Start -Verb RunAs '%0' 2> nul || (
        echo Right-click on the script and select "Run as administrator".
        pause & exit 1
    )
    exit 0
)


:: ----------------------------------------------------------
:: --------------------App Connector app---------------------
:: ----------------------------------------------------------
echo --- App Connector app
PowerShell -ExecutionPolicy Unrestricted -Command "Get-AppxPackage 'Microsoft.Appconnector' | Remove-AppxPackage"
:: ----------------------------------------------------------


pause
exit /b 0
```
## Output
```
λ .\privacy-script.bat
'ttps:' is not recognized as an internal or external command,
operable program or batch file.
--- App Connector app
Press any key to continue . . .
```

**Comment by undergroundwires** [comment]
Thanks for the clarification. I tried to reproduce this but it works as expected for me:

```cmd

J:\> .\test.bat
--- App Connector app
Press any key to continue . . .

```

It's very interesting. I've never heard of this before. Somehow your command line does not seem to understand that `::` in the beginning (with URL) is a comment. However it understands that `::` lines that comes later on (above App Connector app) are actually comments.

1. Can you try to change `::` to `REM` and on line with URL then let me know if it works?
2. Also could you share the OS information (you can get by `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"` from cmd)?

**Comment by playgithub** [comment]
> * Can you try to change `::` to `REM` and on line with URL then let me know if it works?

Replaced the first `::` to `REM`, output
```shell
`https:` is not recognized as an internal or external command.
operable program or batch file.
--- App Connector app
Press any key to continue . . .
```

> * Also could you share the OS information (you can get by `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"` from cmd)?
```
> systeminfo | findstr /B /C:"OS Name" /C:"OS Version
OS Name:          Microsoft Windows 10 Pro N
OS Version:       10.0.19043 N/A Build 19043
```

Remarks: This is the info that's from another computer. My original computer installs `Windows 10 Pro` (without `N`), but now it is running Linux, so I can't test it, I think the result is the same.

**Comment by playgithub** [comment]
I reinstalled Windows 10 Pro, and tried v0.10.3, the problem can not be reproduced.
```shell
λ systeminfo | findstr /B /C:"OS Name" /C:"OS Version
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19043 N/A Build 19043
```
